"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import CustomerDossier from "./CustomerDossier";
function money(v){return `$${Number(v||0).toFixed(2)}`}
function fmtDate(v){return v?new Date(v).toLocaleString():"—"}
function keyFor(name,email){return `vale_deleted_customer_${`${name}::${email}`.toLowerCase()}`}
function hideDeletedCards(){try{document.querySelectorAll(".customerCardButton").forEach(card=>{const text=card.innerText||"",email=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}/i)||[])[0]||"",lines=text.split(/\\n+/).map(x=>x.trim()).filter(Boolean),name=lines.find(x=>x!==email&&!/bookings?|attended|no-show|spent|outstanding/i.test(x))||"";card.style.display=email&&name&&localStorage.getItem(keyFor(name,email))?"none":""})}catch{}}
export default function AdminEnhancements(){
 const [modal,setModal]=useState(null),[customers,setCustomers]=useState([]),[fees,setFees]=useState([]),[bookings,setBookings]=useState([]),[feeOpen,setFeeOpen]=useState(false),[feeSearch,setFeeSearch]=useState(""),[selected,setSelected]=useState(""),[amount,setAmount]=useState(""),[reason,setReason]=useState("Admin fee"),[notify,setNotify]=useState(false),[msg,setMsg]=useState(""),[saving,setSaving]=useState(false);
 const pin=()=>sessionStorage.getItem("vale_admin_pin")||"";
 async function refreshFeeData(){try{const r=await fetch("/api/admin",{headers:{"x-admin-pin":pin()},cache:"no-store"});const j=await r.json();if(r.ok){setCustomers(j.customers||[]);setFees(j.fees||[]);setBookings(j.bookings||[])}}catch{}}
 useEffect(()=>{const onClick=e=>{const card=e.target.closest?.(".customerCardButton");if(!card)return;e.preventDefault();e.stopPropagation();const text=card.innerText||"",email=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}/i)||[])[0]||"",lines=text.split(/\\n+/).map(x=>x.trim()).filter(Boolean),name=lines.find(x=>x!==email&&!/bookings?|attended|no-show|spent|outstanding/i.test(x))||"";fetch("/api/admin",{headers:{"x-admin-pin":pin()},cache:"no-store"}).then(r=>r.json()).then(j=>{const list=j.customers||[];setCustomers(list);const c=list.find(x=>x.email?.toLowerCase()===email.toLowerCase()&&x.name===name)||list.find(x=>x.email?.toLowerCase()===email.toLowerCase());setModal(c||{id:null,name,email,phone:"",address:"",internal_notes:"",bookings:0,attended:0,noShows:0,lateCancels:0,totalSpent:0,outstanding:0,fees:[],discounts:[],history:[]})}).catch(()=>{})};document.addEventListener("click",onClick,true);return()=>document.removeEventListener("click",onClick,true)},[]);
 useEffect(()=>{const onTab=()=>{const active=document.querySelector('.adminTabs .adminTab.active');const next=!!active?.textContent.includes("Fees");setFeeOpen(v=>v===next?v:next);if(next)refreshFeeData()};onTab();document.addEventListener("click",onTab);return()=>document.removeEventListener("click",onTab)},[]);
 useEffect(()=>{hideDeletedCards();const onDeleted=()=>setTimeout(hideDeletedCards,0);window.addEventListener("vale:customer-deleted",onDeleted);return()=>window.removeEventListener("vale:customer-deleted",onDeleted)},[]);
 useEffect(()=>{if(!feeOpen)return;const old=document.querySelector(".adminSplit > .adminCard:first-child");if(old)old.style.display="none";refreshFeeData();return()=>{if(old)old.style.display=""}},[feeOpen]);
 const chosen=customers.find(c=>(c.id&&`id:${c.id}`===selected)||(!c.id&&`email:${c.email}`===selected));
 const feeRows=useMemo(()=>{const q=feeSearch.trim().toLowerCase();return fees.map(f=>{const c=f.customer_id?customers.find(x=>String(x.id)===String(f.customer_id)):null;const b=f.booking_id?bookings.find(x=>String(x.id)===String(f.booking_id)):null;const name=c?.name||b?.name||f.email||"Customer";const email=c?.email||b?.email||f.email||"";return {...f,displayName:name,displayEmail:email}}).filter(f=>!q||`${f.displayName} ${f.displayEmail} ${f.reason||""}`.toLowerCase().includes(q)).sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0))},[fees,customers,bookings,feeSearch]);
 async function addFee(){const c=chosen;if(!c){setMsg("Please choose a customer first.");return}if(!Number.isFinite(Number(amount))||Number(amount)<=0){setMsg("Enter a valid fee amount.");return}if(!confirm(`Add ${money(amount)} fee to ${c.name}?`))return;setSaving(true);setMsg("");try{const r=await fetch("/api/admin/fees",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin()},body:JSON.stringify({customerId:c.id||null,email:c.email,customerName:c.name,amount:Number(amount),reason,notify})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not add the fee.");setMsg(j.message||"Fee added.");setAmount("");setReason("Admin fee");setNotify(false);setSelected("");await refreshFeeData()}catch(e){setMsg(e.message)}finally{setSaving(false)}}
 async function feeAction(f,action){if(!confirm(`${action==="waive_fee"?"Waive":"Mark paid"} ${money(f.amount)} fee for ${f.displayName}?`))return;setSaving(true);setMsg("");try{const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin()},body:JSON.stringify({action,feeId:f.id})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Action failed");setMsg(j.message||"Done");await refreshFeeData()}catch(e){setMsg(e.message)}finally{setSaving(false)}}
 function closeModal(){setModal(null)}
 return <>{modal&&createPortal(<div className="dossierOverlay" role="dialog" aria-modal="true"><div className="dossierOverlayCard"><CustomerDossier customer={modal} onClose={closeModal} onSaved={()=>{}}/></div></div>,document.body)}{feeOpen&&createPortal(<section className="adminCard feeFixCard"><div className="filterHeader"><div><h3>Fee history</h3><p className="muted small">Search by customer name or email. Every fee keeps its added and resolved date.</p></div></div><input className="adminSearch" placeholder="Type the first letters of a name or search email…" value={feeSearch} onChange={e=>setFeeSearch(e.target.value)}/><div className="feeHistoryList">{feeRows.length?feeRows.map(f=><article className="feeHistoryRow" key={f.id}><div className="feeHistoryIdentity"><strong>{f.displayName}</strong><small>{f.displayEmail}</small></div><div className="feeHistoryInfo"><strong>{money(f.amount)}</strong><span>{f.reason||"Admin fee"}</span><small>Fee added: {fmtDate(f.created_at)}</small>{f.resolved_at&&<small>{f.status==="waived"?"Fee waived":"Resolved"}: {fmtDate(f.resolved_at)}</small>}</div><div className="feeHistoryStatus"><span className={`statusBadge status-${f.status}`}>{f.status}</span>{f.status==="outstanding"&&<><button className="textButton" disabled={saving} onClick={()=>feeAction(f,"mark_paid")}>Mark paid</button><button className="textButton dangerText" disabled={saving} onClick={()=>feeAction(f,"waive_fee")}>Waive</button></>}</div></article>):<p className="muted">No fees match your search.</p>}</div><div className="feeAddDivider"/><h3>Add fee</h3><p className="muted small">Choose the customer, enter the fee, then save. The fee is recorded even if email notification fails.</p><div className="form"><input className="adminSearch" placeholder="Type customer name…" value={feeSearch} onChange={e=>{setFeeSearch(e.target.value);setSelected("")}}/><div className="feeCustomerResults">{customers.filter(c=>{const q=feeSearch.trim().toLowerCase();return q&&(`${c.name} ${c.email}`.toLowerCase().includes(q))}).slice(0,8).map(c=><button type="button" key={c.id||`email:${c.email}`} className={chosen?.name===c.name&&chosen?.email===c.email?"feeCustomerChoice selected":"feeCustomerChoice"} onClick={()=>{setSelected(c.id?`id:${c.id}`:`email:${c.email}`);setFeeSearch(c.name)}}><strong>{c.name}</strong><small>{c.email}</small></button>)}</div><input type="number" min="0.01" step="0.01" placeholder="Fee amount" value={amount} onChange={e=>setAmount(e.target.value)}/><input placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><label className="checkLine"><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/> Notify customer by email</label><button className="btn" disabled={saving||!chosen||Number(amount)<=0} onClick={addFee}>{saving?"Saving…":"Add Fee"}</button>{msg&&<p className="muted small">{msg}</p>}</div></section>,document.querySelector(".adminShell")||document.body)}</>}
