"use client";
import {useState} from "react";
function labelTime(mins){const h=Math.floor(mins/60),m=mins%60,s=h>=12?"PM":"AM",hh=h%12||12;return `${hh}:${String(m).padStart(2,"0")} ${s}`}
export default function AdminClient(){
 const [pin,setPin]=useState("");const [rows,setRows]=useState([]);const [fees,setFees]=useState([]);const [msg,setMsg]=useState("");const [loading,setLoading]=useState(false);
 async function load(){const r=await fetch("/api/admin",{headers:{"x-admin-pin":pin},cache:"no-store"});const j=await r.json();if(!r.ok){setMsg(j.error||"Access denied");return}setRows(j.bookings||[]);setFees(j.fees||[]);setMsg("")}
 async function login(e){e.preventDefault();setLoading(true);await load();setLoading(false)}
 async function action(id,action){let amount="";if(action==="no_show"||action==="late_cancel"){amount=prompt("Enter the fee amount (for example 25.00):","");if(amount===null)return}setLoading(true);setMsg("");const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin},body:JSON.stringify({id,action,amount:Number(amount)})});const j=await r.json();setMsg(j.message||j.error||"");await load();setLoading(false)}
 async function feeAction(feeId,action){setLoading(true);setMsg("");const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin},body:JSON.stringify({feeId,action})});const j=await r.json();setMsg(j.message||j.error||"");await load();setLoading(false)}
 return <div className="bookingbox"><form className="form" onSubmit={login}><label>Admin PIN<input type="password" value={pin} onChange={e=>setPin(e.target.value)} required/></label><button className="btn" disabled={loading}>{loading?"Loading…":"Log in"}</button></form>
 {msg&&<p className="success" style={{marginTop:15}}>{msg}</p>}
 {!!rows.length&&<div className="adminList" style={{marginTop:24}}><h2>Appointments</h2>{rows.map(b=><div className="adminBooking" key={b.id}><div className="adminBookingTop"><strong>{b.date} · {labelTime(b.start_minutes)}</strong><span className={`statusBadge status-${b.status}`}>{b.status.replace("_"," ")}</span></div><div>{b.name} · {b.email}</div><div>{b.duration_minutes} min · ${Number(b.total_price).toFixed(2)}</div>{b.notes&&<div className="muted">Notes: {b.notes}</div>}{b.status==="confirmed"&&<div className="adminActions"><button type="button" className="btn smallBtn" onClick={()=>action(b.id,"attended")} disabled={loading}>✓ Attended</button><button type="button" className="btn dangerBtn smallBtn" onClick={()=>action(b.id,"no_show")} disabled={loading}>No-show + fee</button><button type="button" className="btn lateBtn smallBtn" onClick={()=>action(b.id,"late_cancel")} disabled={loading}>Late cancel + fee</button></div>}</div>)}</div>}
 {!!fees.length&&<div className="adminList" style={{marginTop:28}}><h2>Fees</h2>{fees.map(f=><div className="adminBooking" key={f.id}><div><strong>${Number(f.amount).toFixed(2)}</strong> · {f.reason}</div><div>{f.email} · {f.status}</div>{f.status==="outstanding"&&<div className="adminActions"><button type="button" className="btn smallBtn" onClick={()=>feeAction(f.id,"mark_paid")} disabled={loading}>Mark paid</button><button type="button" className="btn smallBtn" onClick={()=>feeAction(f.id,"waive_fee")} disabled={loading}>Waive fee</button></div>}</div>)}</div>}
 </div>
}
