"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import CustomerFiles from "./CustomerFiles";
function money(v){return `$${Number(v||0).toFixed(2)}`}
export default function AdminEnhancements(){
 const [modal,setModal]=useState(null),[customers,setCustomers]=useState([]),[feeOpen,setFeeOpen]=useState(false),[selected,setSelected]=useState(""),[amount,setAmount]=useState(""),[reason,setReason]=useState("Admin fee"),[notify,setNotify]=useState(false),[msg,setMsg]=useState(""),[saving,setSaving]=useState(false);
 const pin=()=>sessionStorage.getItem("vale_admin_pin")||"";
 useEffect(()=>{const scan=()=>{const el=document.querySelector(".profileModal");if(!el){setModal(null);return}const email=el.querySelector('input[type="email"]')?.value||"";const name=el.querySelector(".modalHeader h3")?.textContent||"";setModal({el,email,name})};scan();const o=new MutationObserver(scan);o.observe(document.body,{subtree:true,childList:true,attributes:true});return()=>o.disconnect()},[]);
 useEffect(()=>{const scan=()=>setFeeOpen(!!document.querySelector('.adminTabs .adminTab.active')?.textContent.includes("Fees"));scan();const o=new MutationObserver(scan);o.observe(document.body,{subtree:true,childList:true,attributes:true});return()=>o.disconnect()},[]);
 useEffect(()=>{if(!feeOpen)return;fetch("/api/admin",{headers:{"x-admin-pin":pin()},cache:"no-store"}).then(r=>r.json()).then(j=>setCustomers(j.customers||[])).catch(()=>{});const old=document.querySelector(".adminSplit > .adminCard:first-child");if(old)old.style.display="none";return()=>{if(old)old.style.display=""}},[feeOpen]);
 const profileCustomer=customers.find(c=>c.email?.toLowerCase()===String(modal?.email||"").toLowerCase()&&c.name===modal?.name)||customers.find(c=>c.email?.toLowerCase()===String(modal?.email||"").toLowerCase());
 const chosen=customers.find(c=>(c.id&&`id:${c.id}`===selected)||(!c.id&&`email:${c.email}`===selected));
 async function addFee(){const c=chosen;if(!c){setMsg("Please choose a customer first.");return}if(!Number.isFinite(Number(amount))||Number(amount)<=0){setMsg("Enter a valid fee amount.");return}if(!confirm(`Add ${money(amount)} fee to ${c.name}?`))return;setSaving(true);setMsg("");try{const r=await fetch("/api/admin/fees",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin()},body:JSON.stringify({customerId:c.id||null,email:c.email,customerName:c.name,amount:Number(amount),reason,notify})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not add the fee.");setMsg(j.message||"Fee added.");setAmount("");setReason("Admin fee");setNotify(false);setSelected("");}catch(e){setMsg(e.message)}finally{setSaving(false)}}
 return <>{modal&&profileCustomer&&createPortal(<div className="profileEnhancements"><CustomerFiles customerId={profileCustomer.id} title="General Customer Files"/>{(profileCustomer.history||[]).map(b=><div key={b.id} className="profileBookingEnhancement"><div className="bookingProfileDetails"><b>{b.date} · {b.start_minutes!=null?(()=>{const h=Math.floor(Number(b.start_minutes)/60),m=Number(b.start_minutes)%60,s=h>=12?"PM":"AM",hh=h%12||12;return `${hh}:${String(m).padStart(2,"0")} ${s}`})():""}</b> · {b.status}<br/>{(b.items||[]).map(x=>x.name).join(" · ")} · {money(b.total_price)}<br/>{b.notes&&<>Booking notes: {b.notes}<br/></>}</div><CustomerFiles customerId={profileCustomer.id} bookingId={b.id} title="Session Photos / Files & Notes"/></div>)}</div>,modal.el)}{feeOpen&&createPortal(<section className="adminCard feeFixCard"><h3>Add fee</h3><p className="muted small">Choose the customer, enter the fee, then save. The fee is recorded even if email notification fails.</p><div className="form"><select value={selected} onChange={e=>{setSelected(e.target.value);setMsg("")}}><option value="">Choose customer</option>{customers.map(c=><option key={c.id||`email:${c.email}`} value={c.id?`id:${c.id}`:`email:${c.email}`}>{c.name} · {c.email}</option>)}</select><input type="number" min="0.01" step="0.01" placeholder="Fee amount" value={amount} onChange={e=>setAmount(e.target.value)}/><input placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><label className="checkLine"><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/> Notify customer by email</label><button className="btn" disabled={saving||!chosen||Number(amount)<=0} onClick={addFee}>{saving?"Saving…":"Add Fee"}</button>{msg&&<p className="muted small">{msg}</p>}</div></section>,document.querySelector(".adminShell")||document.body)}</>}
