"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import CustomerDossier from "./CustomerDossier";
function money(v){return `$${Number(v||0).toFixed(2)}`}
function installConfirmedFilter(){const chips=document.querySelector(".filterChips");if(!chips||chips.querySelector(".confirmedFilterChip"))return false;const btn=document.createElement("button");btn.type="button";btn.className="filterChip confirmedFilterChip";btn.textContent="confirmed";btn.onclick=()=>{const active=!btn.classList.contains("active");btn.classList.toggle("active",active);document.querySelectorAll(".adminBooking").forEach(card=>{const badge=card.querySelector(".statusBadge"),status=(badge?.textContent||"").trim().replaceAll(" ","_").toLowerCase();card.style.display=active&&status!=="confirmed"?"none":""})};chips.appendChild(btn);return true}
export default function AdminEnhancements(){
 const [modal,setModal]=useState(null),[customers,setCustomers]=useState([]),[feeOpen,setFeeOpen]=useState(false),[selected,setSelected]=useState(""),[amount,setAmount]=useState(""),[reason,setReason]=useState("Admin fee"),[notify,setNotify]=useState(false),[msg,setMsg]=useState(""),[saving,setSaving]=useState(false);
 const pin=()=>sessionStorage.getItem("vale_admin_pin")||"";
 useEffect(()=>{const onClick=e=>{const card=e.target.closest?.(".customerCardButton");if(!card)return;e.preventDefault();e.stopPropagation();const text=card.innerText||"",email=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||"",lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),name=lines.find(x=>x!==email&&!/bookings?|attended|no-show|spent|outstanding/i.test(x))||"";fetch("/api/admin",{headers:{"x-admin-pin":pin()},cache:"no-store"}).then(r=>r.json()).then(j=>{const list=j.customers||[];setCustomers(list);const c=list.find(x=>x.email?.toLowerCase()===email.toLowerCase()&&x.name===name)||list.find(x=>x.email?.toLowerCase()===email.toLowerCase());setModal(c||{id:null,name,email,phone:"",address:"",internal_notes:"",bookings:0,attended:0,noShows:0,lateCancels:0,totalSpent:0,outstanding:0,fees:[],discounts:[],history:[]})}).catch(()=>{})};document.addEventListener("click",onClick,true);return()=>document.removeEventListener("click",onClick,true)},[]);
 useEffect(()=>{const onTab=()=>{const active=document.querySelector('.adminTabs .adminTab.active');const next=!!active?.textContent.includes("Fees");setFeeOpen(v=>v===next?v:next);if(active?.textContent.includes("Appointments"))setTimeout(()=>installConfirmedFilter(),50)};onTab();document.addEventListener("click",onTab);return()=>document.removeEventListener("click",onTab)},[]);
 useEffect(()=>{if(!feeOpen)return;fetch("/api/admin",{headers:{"x-admin-pin":pin()},cache:"no-store"}).then(r=>r.json()).then(j=>setCustomers(j.customers||[])).catch(()=>{});const old=document.querySelector(".adminSplit > .adminCard:first-child");if(old)old.style.display="none";return()=>{if(old)old.style.display=""}},[feeOpen]);
 const chosen=customers.find(c=>(c.id&&`id:${c.id}`===selected)||(!c.id&&`email:${c.email}`===selected));
 async function addFee(){const c=chosen;if(!c){setMsg("Please choose a customer first.");return}if(!Number.isFinite(Number(amount))||Number(amount)<=0){setMsg("Enter a valid fee amount.");return}if(!confirm(`Add ${money(amount)} fee to ${c.name}?`))return;setSaving(true);setMsg("");try{const r=await fetch("/api/admin/fees",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin()},body:JSON.stringify({customerId:c.id||null,email:c.email,customerName:c.name,amount:Number(amount),reason,notify})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not add the fee.");setMsg(j.message||"Fee added.");setAmount("");setReason("Admin fee");setNotify(false);setSelected("")}catch(e){setMsg(e.message)}finally{setSaving(false)}}
 function closeModal(){setModal(null)}
 return <>{modal&&createPortal(<div className="dossierOverlay" role="dialog" aria-modal="true"><div className="dossierOverlayCard"><CustomerDossier customer={modal} onClose={closeModal} onSaved={()=>{}}/></div></div>,document.body)}{feeOpen&&createPortal(<section className="adminCard feeFixCard"><h3>Add fee</h3><p className="muted small">Choose the customer, enter the fee, then save. The fee is recorded even if email notification fails.</p><div className="form"><select value={selected} onChange={e=>{setSelected(e.target.value);setMsg("")}}><option value="">Choose customer</option>{customers.map(c=><option key={c.id||`email:${c.email}`} value={c.id?`id:${c.id}`:`email:${c.email}`}>{c.name} · {c.email}</option>)}</select><input type="number" min="0.01" step="0.01" placeholder="Fee amount" value={amount} onChange={e=>setAmount(e.target.value)}/><input placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><label className="checkLine"><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/> Notify customer by email</label><button className="btn" disabled={saving||!chosen||Number(amount)<=0} onClick={addFee}>{saving?"Saving…":"Add Fee"}</button>{msg&&<p className="muted small">{msg}</p>}</div></section>,document.querySelector(".adminShell")||document.body)}</>}
