"use client";
import {useEffect,useRef,useState} from "react";
import CustomerFiles from "./CustomerFiles";
function labelTime(mins){const n=Number(mins||0),h=Math.floor(n/60),m=n%60,s=h>=12?"PM":"AM",hh=h%12||12;return `${hh}:${String(m).padStart(2,"0")} ${s}`}
function money(v){return `$${Number(v||0).toFixed(2)}`}
function deadline(b){return new Date(new Date(`${b.date}T00:00:00`).getTime()+Number(b.start_minutes||0)*60000-86400000).toLocaleString()}
export default function CustomerDossier({customer,onClose,onSaved}){
 const [profile,setProfile]=useState(customer),[name,setName]=useState(customer.name||""),[email,setEmail]=useState(customer.email||""),[phone,setPhone]=useState(customer.phone||""),[address,setAddress]=useState(customer.address||""),[notes,setNotes]=useState(customer.internal_notes||""),[avatar,setAvatar]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[photoBusy,setPhotoBusy]=useState(false);
 const inputRef=useRef(null);const pin=()=>window.sessionStorage.getItem("vale_admin_pin")||"";
 useEffect(()=>{let dead=false;(async()=>{try{const r=await fetch("/api/admin/profile",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin()},body:JSON.stringify({customerId:customer.id||"",name:customer.name||name,email:customer.email||email,phone:customer.phone||"",address:customer.address||"",internal_notes:customer.internal_notes||""})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load profile.");if(!dead&&j.profile){setProfile(v=>({...v,...j.profile}));setName(j.profile.name||name);setEmail(j.profile.email||email);setPhone(j.profile.phone||"");setAddress(j.profile.address||"");setNotes(j.profile.internal_notes||"");loadAvatar(j.profile.id)}}catch(e){if(!dead)setMsg(e.message)}})();return()=>{dead=true}},[]);
 async function loadAvatar(id){if(!id)return;try{const r=await fetch(`/api/admin/files?customerId=${encodeURIComponent(id)}`,{headers:{"x-admin-pin":pin()},cache:"no-store"});const j=await r.json();const photo=(j.files||[]).find(f=>f.note==="Profile photo"&&f.mime_type?.startsWith("image/")&&f.url);setAvatar(photo?.url?`${photo.url}${photo.url.includes("?")?"&":"?"}v=${encodeURIComponent(photo.created_at||Date.now())}`:null)}catch{setAvatar(null)}}
 async function save(){setBusy(true);setMsg("");try{const r=await fetch("/api/admin/profile",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin()},body:JSON.stringify({customerId:profile.id||"",name,email,phone,address,internal_notes:notes})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not save profile.");setProfile(v=>({...v,...j.profile}));await loadAvatar(j.profile.id);setMsg("Profile saved.");onSaved?.()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function uploadAvatar(e){const file=e.target.files?.[0];if(!file||!profile.id){setMsg("Save the profile first, then upload a profile photo.");return}if(!file.type.startsWith("image/")){setMsg("Please choose an image file.");e.target.value="";return}if(file.size>10*1024*1024){setMsg("Image must be 10 MB or smaller.");e.target.value="";return}setPhotoBusy(true);setMsg("");try{const fd=new FormData();fd.set("customerId",profile.id);fd.set("file",file);fd.set("note","Profile photo");const r=await fetch("/api/admin/files",{method:"POST",headers:{"x-admin-pin":pin()},body:fd}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not upload photo.");await loadAvatar(profile.id);setMsg("Profile photo saved")}catch(err){setMsg(err.message)}finally{setPhotoBusy(false);e.target.value=""}}
 async function remove(){if(!profile.id){setMsg("Customer profile not found.");return}if(!confirm(`Delete customer profile ${name} (${email})? Historical bookings will be preserved.`))return;setBusy(true);setMsg("");try{const r=await fetch("/api/admin/profile-delete",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":pin()},body:JSON.stringify({customerId:profile.id,name,email})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not delete profile.");onClose?.()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 function jump(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
 return <div className="dossierProfile">
  <div className="dossierHero"><button type="button" className="dossierAvatar dossierAvatarButton" onClick={()=>profile.id&&inputRef.current?.click()} disabled={!profile.id||photoBusy} aria-label="Upload profile photo">{avatar?<img src={avatar} alt="Profile"/>:name.trim().split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"C"}<span className="avatarEdit">{photoBusy?"…":"＋"}</span></button><input ref={inputRef} type="file" accept="image/*" hidden onChange={uploadAvatar}/><div><div className="eyebrow">CLIENT FILE</div><h2>{name||"Customer"}</h2><p>{email}</p>{phone&&<small>{phone}</small>}<div className="avatarHint">Click the photo to upload or change profile picture</div></div><button type="button" className="dossierClose" onClick={onClose}>×</button></div>
  <div className="dossierStats"><button onClick={()=>jump("dossier-bookings")}><b>{profile.bookings}</b><span>Bookings</span></button><button onClick={()=>jump("dossier-attended")}><b>{profile.attended}</b><span>Attended</span></button><button onClick={()=>jump("dossier-noshow")}><b>{profile.noShows}</b><span>No-shows</span></button><button onClick={()=>jump("dossier-late")}><b>{profile.lateCancels}</b><span>Late cancellations</span></button><button onClick={()=>jump("dossier-spent")}><b>{money(profile.totalSpent)}</b><span>Spent</span></button><button onClick={()=>jump("dossier-fees")}><b>{money(profile.outstanding)}</b><span>Outstanding</span></button></div>
  <section className="dossierSection" id="dossier-general"><div className="dossierSectionTitle"><span>01</span><h3>General profile</h3></div><div className="dossierGrid"><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Address<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="dossierFull">Internal notes<textarea rows="4" value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{profile.id&&<div className="generalFilesInline"><CustomerFiles customerId={profile.id} title="General customer files & photos"/></div>}</section>
  <section className="dossierSection" id="dossier-bookings"><div className="dossierSectionTitle"><span>02</span><h3>Booking history</h3></div>{(profile.history||[]).length?(profile.history||[]).map((b,i)=>{const end=Number(b.start_minutes||0)+Number(b.duration_minutes||0),blocked=end+30;return <article className="dossierBooking" key={b.id||i}><div className="dossierBookingHead"><div><b>{b.date} · {labelTime(b.start_minutes)}</b><span>{b.status}</span></div><strong>{money(b.total_price)}</strong></div><div className="dossierBookingMeta"><div><b>Services</b>{(b.items||[]).map((x,j)=><p key={j}>{x.name} · {x.duration||0} min · {money(x.price)}</p>)}</div><div><b>Timing</b><p>{labelTime(b.start_minutes)} → {labelTime(end)}</p><p>30 min buffer: {labelTime(end)} → {labelTime(blocked)}</p><p>System blocked: {labelTime(b.start_minutes)} → {labelTime(blocked)}</p></div><div><b>Price</b><p>Subtotal {money(b.subtotal_price??b.total_price)}</p><p>Discount -{money(b.discount_amount)}</p><p><strong>Final {money(b.total_price)}</strong></p></div></div>{b.notes&&<p className="dossierNote"><b>Booking notes:</b> {b.notes}</p>}<p className="dossierDeadline">24h self-service deadline: {deadline(b)}</p>{profile.id&&b.id&&<CustomerFiles customerId={profile.id} bookingId={b.id} title="Session photos, files & notes"/>}</article>}) : <p className="muted">No booking history yet.</p>}</section>
  <section className="dossierSection" id="dossier-attended"><div className="dossierSectionTitle"><span>03</span><h3>Attendance</h3></div><p>Attended: <b>{profile.attended}</b> · No-shows: <b>{profile.noShows}</b> · Late cancellations: <b>{profile.lateCancels}</b></p></section>
  <section className="dossierSection" id="dossier-noshow"><div className="dossierSectionTitle"><span>04</span><h3>No-show history</h3></div>{(profile.history||[]).filter(b=>b.status==="no_show").map(b=><div className="dossierRow" key={b.id}>{b.date} · {labelTime(b.start_minutes)} <span>No-show</span></div>)}{!(profile.history||[]).some(b=>b.status==="no_show")&&<p className="muted">No no-shows recorded.</p>}</section>
  <section className="dossierSection" id="dossier-late"><div className="dossierSectionTitle"><span>05</span><h3>Late cancellation history</h3></div>{(profile.history||[]).filter(b=>b.status==="late_cancel").map(b=><div className="dossierRow" key={b.id}>{b.date} · {labelTime(b.start_minutes)} <span>Late cancellation</span></div>)}{!(profile.history||[]).some(b=>b.status==="late_cancel")&&<p className="muted">No late cancellations recorded.</p>}</section>
  <section className="dossierSection" id="dossier-spent"><div className="dossierSectionTitle"><span>06</span><h3>Spending</h3></div><p>Total confirmed/attended spend: <b>{money(profile.totalSpent)}</b></p></section>
  <section className="dossierSection" id="dossier-fees"><div className="dossierSectionTitle"><span>07</span><h3>Fees</h3></div>{(profile.fees||[]).map(f=><div className="dossierRow" key={f.id}><span>{money(f.amount)} · {f.reason}</span><span>{f.status}</span></div>)}{!(profile.fees||[]).length&&<p className="muted">No fees recorded.</p>}</section>
  <section className="dossierSection"><div className="dossierSectionTitle"><span>08</span><h3>Discounts</h3></div>{(profile.discounts||[]).map(d=><div className="dossierRow" key={d.id}><span>{d.kind==="percent"?`${d.value}%`:money(d.value)} · uses {d.uses}{d.max_uses?`/${d.max_uses}`:""}</span><span>{d.active?"Active":"Inactive"}</span></div>)}{!(profile.discounts||[]).length&&<p className="muted">No discounts recorded.</p>}</section>
  <div className="dossierActions"><button className="btn" disabled={busy} onClick={save}>{busy?"Saving…":"Save Profile"}</button><button className="textButton dangerText" disabled={busy} onClick={remove}>Delete Profile</button><button className="textButton" onClick={onClose}>Close</button></div>{msg&&<div className="dossierMessage">{msg}</div>}
 </div>
}
