"use client";
import {useEffect,useState} from "react";
function fmt(v){return v?new Date(v).toLocaleString():"—"}
export default function CustomerFiles({customerId,bookingId=null,title="Photos & Files"}){
 const [files,setFiles]=useState([]),[loading,setLoading]=useState(false),[note,setNote]=useState(""),[msg,setMsg]=useState("");
 async function load(){const pin=window.sessionStorage.getItem("vale_admin_pin")||"";const q=new URLSearchParams({customerId});if(bookingId)q.set("bookingId",bookingId);const r=await fetch(`/api/admin/files?${q}`,{headers:{"x-admin-pin":pin},cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load files.");setFiles(j.files||[])}
 useEffect(()=>{if(customerId)load().catch(e=>setMsg(e.message))},[customerId,bookingId]);
 async function add(e){e.preventDefault();const file=e.currentTarget.elements.file.files[0];if(!file&&!note.trim())return;setLoading(true);setMsg("");try{const fd=new FormData();fd.set("customerId",customerId);if(bookingId)fd.set("bookingId",bookingId);if(file)fd.set("file",file);if(note.trim())fd.set("note",note.trim());const pin=window.sessionStorage.getItem("vale_admin_pin")||"";const r=await fetch("/api/admin/files",{method:"POST",headers:{"x-admin-pin":pin},body:fd}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not save.");setNote("");e.currentTarget.reset();await load();setMsg(j.message||"Saved.")}catch(e){setMsg(e.message)}finally{setLoading(false)}}
 async function del(id){if(!window.confirm("Delete this file/note permanently?"))return;setLoading(true);setMsg("");try{const pin=window.sessionStorage.getItem("vale_admin_pin")||"";const r=await fetch("/api/admin/files",{method:"DELETE",headers:{"content-type":"application/json","x-admin-pin":pin},body:JSON.stringify({id})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not delete.");await load();setMsg("Deleted.")}catch(e){setMsg(e.message)}finally{setLoading(false)}}
 return <section className="profileSection fileManager"><div className="fileManagerHead"><h4>{title}</h4>{bookingId&&<span className="muted small">Files saved only to this booking</span>}</div><form onSubmit={add} className="fileUploadForm"><input name="file" type="file" accept="image/*,.pdf,.doc,.docx,.txt"/><textarea value={note} onChange={e=>setNote(e.target.value)} rows="2" placeholder={bookingId?"Session notes for this booking…":"General customer note (optional)…"}/><button className="btn smallBtn" disabled={loading}>Add file / note</button></form>{msg&&<p className="muted small">{msg}</p>}<div className="fileGrid">{files.length?files.map(f=><div className="fileCard" key={f.id}>{f.url&&f.mime_type?.startsWith("image/")&&<img src={f.url} alt={f.file_name||"Customer photo"}/>}<div className="fileMeta">{f.file_name&&f.url?<a href={f.url} target="_blank" rel="noreferrer">{f.file_name}</a>:<strong>Note</strong>}<small>{fmt(f.created_at)}</small>{f.note&&<p>{f.note}</p>}<button type="button" className="textButton dangerText" disabled={loading} onClick={()=>del(f.id)}>Delete</button></div></div>):<p className="muted small">No files or notes yet.</p>}</div></section>
}
