"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {business,allServices} from "../../lib/services";
import {buildDiscountMessage} from "../../lib/discountMessages";
const money=v=>`$${Number(v||0).toFixed(2)}`;
const blankRule=()=>({serviceIds:[],kind:"percent",value:""});
const blankGroup=()=>({customerIds:[],rules:[blankRule()],startsAt:"",expiresAt:"",maxUses:"",note:"",sameDates:false});
function CustomerPicker({customers,value,onChange}){
 const[q,setQ]=useState(""),[remote,setRemote]=useState([]),[known,setKnown]=useState([]);
 const mergedKnown=[...customers,...known,...remote].filter((c,i,a)=>c?.id&&!a.some((x,j)=>j<i&&x.id===c.id));
 const selected=mergedKnown.filter(c=>value.includes(c.id));
 const local=customers.filter(c=>!q||`${c.name||""} ${c.email||""}`.toLowerCase().includes(q.toLowerCase()));
 const merged=[...local,...remote.filter(r=>!local.some(c=>c.id===r.id))].slice(0,15);
 useEffect(()=>{const term=q.trim();if(!term){setRemote([]);return}const controller=new AbortController();const timer=setTimeout(async()=>{try{const r=await fetch(`/api/customers?q=${encodeURIComponent(term)}`,{cache:"no-store",signal:controller.signal});const j=await r.json();setRemote(j.customers||[]);setKnown(prev=>[...prev,...(j.customers||[])])}catch{if(!controller.signal.aborted)setRemote([])}},160);return()=>{clearTimeout(timer);controller.abort()}},[q]);
 return <div className="discountCustomerPicker"><div className="discountSelectedList">{selected.map(c=><button type="button" className="selectedCustomer" key={c.id} onClick={()=>onChange(value.filter(id=>id!==c.id))}>{c.name} · {c.email} ×</button>)}</div><input placeholder="Search name or email…" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<div className="customerSuggestions">{merged.map(c=><button type="button" key={c.id} onClick={()=>{if(!value.includes(c.id))onChange([...value,c.id]);setQ("")}}><strong>{c.name}</strong><span>{c.email}</span></button>)}{!merged.length&&<div className="muted small" style={{padding:10}}>No customer found.</div>}</div>}</div>;
}
function ServiceChoices({value,onChange}){return <div className="discountServiceChoices">{allServices.map(s=><label key={s.id} className="checkLine"><input type="checkbox" checked={value.includes(s.id)} onChange={()=>onChange(value.includes(s.id)?value.filter(id=>id!==s.id):[...value,s.id])}/><span>{s.name} — {money(s.price)}</span></label>)}</div>}
function Rule({rule,index,onChange,onRemove,canRemove}){return <div className="discountRule"><div className="discountRuleHeader"><strong>Service discount {index+1}</strong>{canRemove&&<button type="button" className="removeGroup" onClick={onRemove}>Remove</button>}</div><label>Apply to service(s)<ServiceChoices value={rule.serviceIds} onChange={v=>onChange({...rule,serviceIds:v})}/></label><div className="discountValueRow"><label>Discount type<select value={rule.kind} onChange={e=>onChange({...rule,kind:e.target.value})}><option value="percent">Percent %</option><option value="fixed">Fixed $</option></select></label><label>Discount value<input type="number" min="0.01" step="0.01" placeholder={rule.kind==="percent"?"e.g. 50":"e.g. 25"} value={rule.value} onChange={e=>onChange({...rule,value:e.target.value})}/></label></div></div>}
export default function DiscountManager(){
 const[pin,setPin]=useState(""),[target,setTarget]=useState(null),[customers,setCustomers]=useState([]),[scope,setScope]=useState("customer"),[groups,setGroups]=useState([blankGroup()]),[occasion,setOccasion]=useState(""),[notify,setNotify]=useState(false),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const findTarget=()=>{const nodes=[...document.querySelectorAll(".adminSplit")];const section=nodes.flatMap(n=>[...n.querySelectorAll(":scope > .adminCard")]).find(s=>s.querySelector("h3")?.textContent.trim()==="Discounts");setTarget(section||null);if(section)section.classList.add("discountManagerHost")};findTarget();const observer=new MutationObserver(findTarget);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();document.querySelectorAll(".discountManagerHost").forEach(x=>x.classList.remove("discountManagerHost"))}},[]);
 useEffect(()=>{const p=sessionStorage.getItem("vale_admin_pin")||"";setPin(p);if(!p)return;fetch("/api/admin",{headers:{"x-admin-pin":p},cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||"Could not load customers.");setCustomers(j.customers||[])}).catch(e=>setMsg(e.message))},[]);
 function updateGroup(i,next){setGroups(v=>v.map((g,n)=>n===i?next:g))}
 function updateRule(gi,ri,next){updateGroup(gi,{...groups[gi],rules:groups[gi].rules.map((r,n)=>n===ri?next:r)})}
 function addRule(i){updateGroup(i,{...groups[i],rules:[...groups[i].rules,blankRule()]})}
 function removeRule(gi,ri){updateGroup(gi,{...groups[gi],rules:groups[gi].rules.length===1?groups[gi].rules:groups[gi].rules.filter((_,n)=>n!==ri)})}
 function addGroup(){setGroups(v=>[...v,blankGroup()])}
 function removeGroup(i){setGroups(v=>v.length===1?v:v.filter((_,n)=>n!==i))}
 function groupDates(i){if(i>0&&groups[i].sameDates){const p=groups[i-1];return {startsAt:p.startsAt,expiresAt:p.expiresAt}}return {startsAt:groups[i].startsAt,expiresAt:groups[i].expiresAt}}
 async function save(){
  const prepared=groups.map((g,i)=>{const d=groupDates(i);return {...g,...d}});
  if(scope!=="customer"){const g=prepared[0];if(!g.rules.length)return setMsg("Add at least one service discount.");if(g.expiresAt&&g.startsAt&&new Date(g.expiresAt)<=new Date(g.startsAt))return setMsg("End date/time must be after the start date/time.");if(g.maxUses&&(!Number.isInteger(Number(g.maxUses))||Number(g.maxUses)<1))return setMsg("Maximum uses must be a positive whole number.");for(const r of g.rules){if(!r.serviceIds.length||!Number.isFinite(Number(r.value))||Number(r.value)<=0)return setMsg("Every service discount needs a service and a valid value.");if(r.kind==="percent"&&Number(r.value)>100)return setMsg("Percent discounts cannot be more than 100%.")}setBusy(true);setMsg("");try{const currentPin=sessionStorage.getItem("vale_admin_pin")||pin;if(!currentPin)throw Error("Admin session expired. Please log in again.");const payload={action:"service_discount",discountGroups:g.rules.map(r=>({serviceIds:r.serviceIds,kind:r.kind,value:Number(r.value)})),startsAt:g.startsAt||null,expiresAt:g.expiresAt||null,maxUses:g.maxUses||null,note:g.note,occasion:occasion.trim(),notify};const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":currentPin},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw Error(j.error||"Could not activate service discounts.");setMsg(j.message||"Service discounts activated.");setGroups([blankGroup()]);setOccasion("");setNotify(false);window.dispatchEvent(new Event("vale-admin-reload"))}catch(e){setMsg(e.message)}finally{setBusy(false)}return;}

  for(const g of prepared){if(!g.customerIds.length)return setMsg("Choose at least one customer for every discount group.");if(!g.rules.length)return setMsg("Add at least one service discount.");if(g.expiresAt&&g.startsAt&&new Date(g.expiresAt)<=new Date(g.startsAt))return setMsg("End date/time must be after the start date/time.");if(g.maxUses&&(!Number.isInteger(Number(g.maxUses))||Number(g.maxUses)<1))return setMsg("Maximum uses must be a positive whole number.");const seen=new Set();for(const r of g.rules){if(!r.serviceIds.length||!Number.isFinite(Number(r.value))||Number(r.value)<=0)return setMsg("Every service discount needs a service and a valid value.");if(r.kind==="percent"&&Number(r.value)>100)return setMsg("Percent discounts cannot be more than 100%.");for(const id of r.serviceIds){if(seen.has(id))return setMsg("A service can only appear once within the same discount group.");seen.add(id)}}}
  setBusy(true);setMsg("");try{const currentPin=sessionStorage.getItem("vale_admin_pin")||pin;if(!currentPin)throw Error("Admin session expired. Please log in again.");const payload={discountGroups:prepared.map(g=>({customerIds:g.customerIds,rules:g.rules.map(r=>({serviceIds:r.serviceIds,kind:r.kind,value:Number(r.value)})),startsAt:g.startsAt||null,expiresAt:g.expiresAt||null,maxUses:g.maxUses||null,note:g.note, sameDates:g.sameDates})),notify:true,occasion:occasion.trim()};const r=await fetch("/api/admin/discount-groups",{method:"POST",headers:{"content-type":"application/json","x-admin-pin":currentPin},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw Error(j.error||"Could not activate discounts.");setMsg(j.message||"Discounts activated.");setGroups([blankGroup()]);setOccasion("");setNotify(false)}catch(e){setMsg(e.message)}finally{setBusy(false)}
 }
 if(!target)return null;
 const content=<><style jsx global>{`.discountManagerHost>.form{display:none!important}.discountManagerHost>.discountManager{display:block}.discountManager{margin-top:8px}.discountCustomerPicker{position:relative}.discountSelectedList{display:grid;gap:6px;margin-bottom:8px}.discountSelectedList:empty{display:none}.discountGroup{border:1px solid var(--line);padding:14px;margin:10px 0;background:#fff}.discountGroupHeader,.discountRuleHeader{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:9px}.discountGroupHeader strong,.discountRuleHeader strong{font-size:15px}.discountRule{border-top:1px solid #eee;padding-top:12px;margin-top:12px}.discountServiceChoices{display:grid;gap:6px;max-height:220px;overflow:auto;padding:8px;border:1px solid var(--line);background:#fff}.discountValueRow{display:grid;grid-template-columns:minmax(150px,1fr) minmax(130px,1fr);gap:10px;margin-top:10px}.discountManagerActions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.discountHelp{margin:5px 0 10px}.discountManager label{display:grid;gap:5px}.discountManager .checkLine{display:flex;align-items:center;gap:8px}.discountManager .checkLine input{width:auto}.discountManager textarea{width:100%;resize:vertical}.discountManager input,.discountManager select,.discountManager textarea{box-sizing:border-box}.discountManager .removeGroup{border:0;background:none;padding:4px 0;color:#a55;cursor:pointer}.discountManager .customerSuggestions{z-index:40;position:absolute;left:0;right:0;background:#fff;border:1px solid var(--line);box-shadow:0 8px 20px rgba(0,0,0,.08);max-height:260px;overflow:auto}.discountManager .customerSuggestions button{display:grid;width:100%;text-align:left;border:0;background:#fff;padding:9px 10px;cursor:pointer;gap:2px}.discountManager .customerSuggestions button:hover{background:#f8f1ef}.discountSameDates{display:flex!important;align-items:center;gap:8px;margin-top:12px}.discountSameDates input{width:auto!important}.discountNotificationBox{border-top:1px solid var(--line);margin-top:16px;padding-top:14px;display:grid;gap:10px}.discountNotifyLine{display:flex!important;align-items:center;gap:8px}.discountNotifyLine input{width:auto!important}.discountPreview{border:1px solid var(--line);background:#faf7f5;padding:12px}.discountPreviewBody{background:#fff;border:1px solid #eee;padding:12px;margin-top:8px;max-height:280px;overflow:auto}.discountPreviewBody h2{font-size:18px;margin:0 0 10px}.discountPreviewBody p{margin:8px 0;line-height:1.5}`}</style>
 <section className="adminCard discountManager" style={{marginTop:8}}><p className="muted small discountHelp">Create one or more discount groups. Each group can contain multiple customers and different service discounts, with its own dates, usage limit and note. Each customer receives one personalized email.</p>
 {scope==="customer"&&groups.map((g,i)=>{const dates=groupDates(i);return <div className="discountGroup" key={i}><div className="discountGroupHeader"><strong>Discount Group {i+1}</strong>{groups.length>1&&<button type="button" className="removeGroup" onClick={()=>removeGroup(i)}>Remove group</button>}</div><label>Customer(s)<CustomerPicker customers={customers} value={g.customerIds} onChange={v=>updateGroup(i,{...g,customerIds:v})}/></label>{g.rules.map((r,ri)=><Rule key={ri} rule={r} index={ri} onChange={next=>updateRule(i,ri,next)} onRemove={()=>removeRule(i,ri)} canRemove={g.rules.length>1}/>)}<button type="button" className="textButton" onClick={()=>addRule(i)}>+ Add another service discount</button><div style={{display:"grid",gap:10,marginTop:14}}><label>Start date/time <span className="muted small">(optional — blank means now)</span><input type="datetime-local" value={dates.startsAt} disabled={i>0&&g.sameDates} onChange={e=>updateGroup(i,{...g,startsAt:e.target.value})}/></label><label>End date/time <span className="muted small">(optional)</span><input type="datetime-local" value={dates.expiresAt} disabled={i>0&&g.sameDates} onChange={e=>updateGroup(i,{...g,expiresAt:e.target.value})}/></label>{i>0&&<label className="discountSameDates"><input type="checkbox" checked={g.sameDates} onChange={e=>updateGroup(i,{...g,sameDates:e.target.checked})}/> Same start &amp; end date/time as Discount Group {i}</label>}<label>Maximum uses per discount <span className="muted small">(optional)</span><input type="number" min="1" step="1" placeholder="No limit" value={g.maxUses} onChange={e=>updateGroup(i,{...g,maxUses:e.target.value})}/></label><label>Note <span className="muted small">(optional)</span><textarea rows="2" placeholder="Optional note" value={g.note} onChange={e=>updateGroup(i,{...g,note:e.target.value})}/></label></div></div>})}
 {scope!=="customer"&&<div className="discountGroup"><div className="discountGroupHeader"><strong>Service Discounts for Everyone</strong></div>{groups[0].rules.map((r,ri)=><Rule key={ri} rule={r} index={ri} onChange={next=>updateRule(0,ri,next)} onRemove={()=>removeRule(0,ri)} canRemove={groups[0].rules.length>1}/>)}<button type="button" className="textButton" onClick={()=>addRule(0)}>+ Add another service discount</button><div style={{display:"grid",gap:10,marginTop:14}}><label>Start date/time <span className="muted small">(optional — blank means now)</span><input type="datetime-local" value={groups[0].startsAt} onChange={e=>updateGroup(0,{...groups[0],startsAt:e.target.value})}/></label><label>End date/time <span className="muted small">(optional)</span><input type="datetime-local" value={groups[0].expiresAt} onChange={e=>updateGroup(0,{...groups[0],expiresAt:e.target.value})}/></label><label>Maximum uses per discount <span className="muted small">(optional)</span><input type="number" min="1" step="1" placeholder="No limit" value={groups[0].maxUses} onChange={e=>updateGroup(0,{...groups[0],maxUses:e.target.value})}/></label><label>Note <span className="muted small">(optional)</span><textarea rows="2" placeholder="Optional note" value={groups[0].note} onChange={e=>updateGroup(0,{...groups[0],note:e.target.value})}/></label></div></div>}
 {scope==="customer"&&<button type="button" className="textButton" onClick={addGroup}>+ Add another discount</button>}<div className="discountNotificationBox"><label>Occasion / celebration <span className="muted small">(optional — type it naturally, e.g. Birthday, Wedding Anniversary, Ramadan, Labour Day)</span><input value={occasion} onChange={e=>setOccasion(e.target.value)} placeholder="e.g. Birthday or عيد زواج"/></label>{scope==="service"&&<label className="discountNotifyLine"><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/><span>Notify all customers with a profile by email</span></label>}{(scope==="customer"||notify)&&<div className="discountPreview"><div className="muted small">Email preview</div>{(()=>{const previewGroups=groups[0]?.rules||[];const previewName=scope==="customer"?(customers.find(c=>c.id===groups[0]?.customerIds?.[0])?.name||"Customer"):"";const preview=buildDiscountMessage({name:previewName,occasion,groups:previewGroups,allServices,businessName:business.name,audience:scope==="customer"?"personal":"everyone"});return <><strong>{preview.subject}</strong><div className="discountPreviewBody" dangerouslySetInnerHTML={{__html:preview.html}}/></>})()}</div>}</div><label style={{marginTop:14}}>Discount scope<select value={scope} onChange={e=>setScope(e.target.value)}><option value="customer">Customer-specific discount</option><option value="service">Service discount for everyone</option></select></label><div className="discountManagerActions"><button type="button" className="btn" disabled={busy} onClick={save}>{busy?"Saving…":"Activate Discount(s)"}</button></div>{msg&&<div className={msg.toLowerCase().includes("activated")?"success":"error"} style={{marginTop:12}}>{msg}</div>}</section></>;
 return createPortal(content,target);
}
