import {NextResponse} from "next/server";
import {sendMail} from "../../../../lib/mailer";
import {business} from "../../../../lib/services";
import {createClient} from "@supabase/supabase-js";
const db=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const ok=req=>req.headers.get("x-admin-pin")===process.env.ADMIN_PIN;
const MAX_TOTAL=3*1024*1024;
function sanitize(html=""){return String(html).replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<style[\s\S]*?<\/style>/gi,"").replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi,"").replace(/javascript:/gi,"").replace(/<iframe[\s\S]*?<\/iframe>/gi,"")}
function normalizeAttachments(input){if(!Array.isArray(input))return [];const out=[];let total=0;for(const a of input.slice(0,5)){const content=String(a?.content||"");if(!content)continue;const size=Math.ceil(content.length*3/4);if(size>2*1024*1024||total+size>MAX_TOTAL)continue;const filename=String(a?.filename||"attachment").slice(0,180);const contentType=String(a?.contentType||"application/octet-stream").slice(0,120);const cid=a?.cid?String(a.cid).replace(/[^a-zA-Z0-9._-]/g,""):undefined;out.push({filename,content,contentType,cid});total+=size}return out}
export async function POST(req){if(!ok(req))return NextResponse.json({error:"Access denied"},{status:403});try{const body=await req.json(),recipients=Array.isArray(body.recipients)?[...new Set(body.recipients.map(x=>String(x).trim().toLowerCase()).filter(Boolean))]:[],subject=String(body.subject||"").trim(),html=sanitize(body.html||""),attachments=normalizeAttachments(body.attachments);if(!recipients.length||!subject||!html)return NextResponse.json({error:"Choose recipients and enter a subject and message."},{status:400});const wrapped=`<div style="font-family:Arial,sans-serif;line-height:1.6;color:#1f2937">${html}<hr><p>${business.name}<br>${business.email}<br>${business.phone}<br>${business.address}</p></div>`;let sent=0;for(const email of recipients){try{const result=await sendMail({to:email,subject,html:wrapped,attachments});if(!result?.rejected?.length)sent++;}catch(e){console.error("RICH MESSAGE EMAIL FAILED",e)}}await db().from("admin_audit_log").insert({action:"send_customer_email",entity_type:"message",entity_id:"",email:recipients[0]||null,details:{recipients,subject,sent,requested:recipients.length,attachmentCount:attachments.length}}).then(({error})=>{if(error)console.error("MESSAGE AUDIT FAILED",error)});return NextResponse.json({message:`Message sent to ${sent} of ${recipients.length} selected customers.`})}catch(e){console.error(e);return NextResponse.json({error:"Could not send this email."},{status:500})}}
