function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function normalize(v=""){return String(v).trim().toLowerCase().normalize("NFKD").replace(/[\u064B-\u065F\u0670]/g,"").replace(/[ًٌٍَُِّْـ]/g,"")}
const patterns=[
 {key:"birthday",terms:["birthday","bday","birth day","عيد ميلاد","ميلاد"],subject:"Happy Birthday from VALE BEAUTY 🎂",heading:n=>"Happy Birthday"+(n?", "+n:"")+"! 🎂",body:"Wishing you a beautiful birthday filled with happiness, love, and beautiful moments."},
 {key:"anniversary",terms:["anniversary","wedding anniversary","عيد زواج","ذكرى زواج","ذكرى الزواج","ذكرى زفاف"],subject:"A Little Anniversary Gift from VALE BEAUTY 💕",heading:n=>"Happy Anniversary"+(n?", "+n:"")+"! 💕",body:"Wishing you both another beautiful year filled with love, happiness, and wonderful memories."},
 {key:"wedding",terms:["wedding","bride","bridal","getting married","engagement","زواج","زفاف","عرس","عروس","خطوبة"],subject:"A Little Celebration from VALE BEAUTY 💍",heading:n=>"Congratulations"+(n?", "+n:"")+"! 💍",body:"Wishing you a beautiful celebration and all the happiness in this exciting chapter."},
 {key:"ramadan",terms:["ramadan","رمضان"],subject:"Ramadan Mubarak from VALE BEAUTY 🌙",heading:n=>"Ramadan Mubarak"+(n?", "+n:"")+"! 🌙",body:"Wishing you a peaceful, joyful Ramadan filled with beautiful moments and blessings."},
 {key:"labour",terms:["labour day","labor day","عيد العمال"],subject:"A Little Labour Day Treat from VALE BEAUTY ✨",heading:()=>"Happy Labour Day! ✨",body:"We hope you enjoy a relaxing long weekend and a little time for yourself."},
 {key:"eid",terms:["eid","eid al-fitr","eid al adha","عيد الفطر","عيد الاضحى","عيد الأضحى","عيد"],subject:"Eid Mubarak from VALE BEAUTY ✨",heading:n=>"Eid Mubarak"+(n?", "+n:"")+"! ✨",body:"Wishing you and your loved ones a beautiful Eid filled with happiness and joy."},
 {key:"canadaday",terms:["canada day","july 1","عيد كندا","يوم كندا"],subject:"A Little Canada Day Treat from VALE BEAUTY 🍁",heading:()=>"Happy Canada Day! 🍁",body:"Wishing you a beautiful Canada Day filled with sunshine, happiness, and a little time for yourself."},
 {key:"thanksgiving",terms:["thanksgiving","عيد الشكر"],subject:"A Little Thanksgiving Treat from VALE BEAUTY 🧡",heading:n=>"Happy Thanksgiving"+(n?", "+n:"")+"! 🧡",body:"Wishing you a warm and beautiful Thanksgiving filled with gratitude and good moments."},
 {key:"easter",terms:["easter","عيد الفصح"],subject:"A Little Easter Treat from VALE BEAUTY 🌷",heading:n=>"Happy Easter"+(n?", "+n:"")+"! 🌷",body:"Wishing you a beautiful Easter filled with peace, happiness, and fresh beginnings."},
 {key:"blackfriday",terms:["black friday","black-friday"],subject:"Black Friday Beauty Treat from VALE BEAUTY 🖤",heading:()=>"A Little Black Friday Treat! 🖤",body:"We’re celebrating with a special beauty offer made just for you."},
 {key:"womensday",terms:["international women's day","international womens day","women's day","womens day","يوم المرأة","عيد المرأة"],subject:"A Little Celebration of You from VALE BEAUTY 💐",heading:n=>"Happy Women's Day"+(n?", "+n:"")+"! 💐",body:"Today is a beautiful reminder to celebrate yourself, your strength, and everything that makes you you."},
 {key:"valentines",terms:["valentine","valentine's day","valentines day","عيد الحب"],subject:"A Little Love from VALE BEAUTY 💕",heading:n=>"Happy Valentine's Day"+(n?", "+n:"")+"! 💕",body:"Sending a little extra love your way and wishing you a beautiful day."},
 {key:"mothers",terms:["mother's day","mothers day","عيد الام","عيد الأم"],subject:"A Little Mother's Day Gift from VALE BEAUTY 💐",heading:n=>"Happy Mother's Day"+(n?", "+n:"")+"! 💐",body:"Wishing you a beautiful day filled with love, appreciation, and a little time for yourself."},
 {key:"fathers",terms:["father's day","fathers day","عيد الاب","عيد الأب"],subject:"A Little Father's Day Gift from VALE BEAUTY ✨",heading:n=>"Happy Father's Day"+(n?", "+n:"")+"! ✨",body:"Wishing you a wonderful Father's Day and a beautiful day with the people you love."},
 {key:"christmas",terms:["christmas","xmas","عيد الميلاد المجيد","كريسماس"],subject:"Merry Christmas from VALE BEAUTY 🎄",heading:n=>"Merry Christmas"+(n?", "+n:"")+"! 🎄",body:"Wishing you a warm, joyful holiday season filled with beautiful moments."},
 {key:"newyear",terms:["new year","new year's","رأس السنة","راس السنة","السنة الجديدة"],subject:"Happy New Year from VALE BEAUTY ✨",heading:n=>"Happy New Year"+(n?", "+n:"")+"! ✨",body:"Wishing you a beautiful year ahead filled with happiness, health, and wonderful new memories."},
 {key:"backtoschool",terms:["back to school","back-to-school","العودة للمدارس","العودة للمدرسة"],subject:"Back-to-School Treat from VALE BEAUTY ✨",heading:n=>"A Little Back-to-School Treat"+(n?", "+n:"")+"! ✨",body:"A new season is here, so we thought you deserved a little self-care before the busy days begin."},
 {key:"newbaby",terms:["new baby","baby shower","newborn","مولود","بيبي","ولادة"],subject:"A Little Gift for Your Special Moment from VALE BEAUTY 💕",heading:n=>"Congratulations"+(n?", "+n:"")+"! 💕",body:"Wishing you and your family so much happiness during this beautiful new chapter."},
 {key:"graduation",terms:["graduation","graduate","تخرج","تخرجك"],subject:"Congratulations from VALE BEAUTY 🎓",heading:n=>"Congratulations"+(n?", "+n:"")+"! 🎓",body:"You worked for this moment, and you deserve to celebrate it. Wishing you every success in what comes next."}
];
function classify(occasion=""){const n=normalize(occasion);return patterns.find(p=>p.terms.some(t=>n.includes(normalize(t))))||null}
function formatValue(g){return g.kind==="percent"?Number(g.value)+"% off":"$"+Number(g.value).toFixed(2)+" off"}
function serviceNames(groups,allServices=[]){return groups.flatMap(g=>(g.serviceIds||[]).map(id=>allServices.find(s=>s.id===id)?.name||id)).filter(Boolean)}
export function buildDiscountMessage({name="",occasion="",groups=[],allServices=[],businessName="VALE BEAUTY VK",audience="personal"}={}){
 const raw=String(occasion||"").trim(),match=classify(raw),person=String(name||"").trim(),safeName=esc(person),safeOccasion=esc(raw);
 const publicSubject={birthday:"A Birthday Treat from VALE BEAUTY 🎂",anniversary:"A Little Anniversary Celebration from VALE BEAUTY 💕",wedding:"A Little Celebration from VALE BEAUTY 💍",newbaby:"A Little Celebration from VALE BEAUTY 💕",graduation:"A Little Celebration from VALE BEAUTY 🎓"};
 const publicHeading={birthday:"A Little Birthday Treat for You! 🎂",anniversary:"A Little Anniversary Treat for You! 💕",wedding:"A Little Celebration for You! 💍",newbaby:"A Little Celebration for You! 💕",graduation:"A Little Celebration for You! 🎓"};
 const title=audience==="everyone"&&match?.key&&publicSubject[match.key]?publicSubject[match.key]:(match?.subject||businessName+" — A Special "+(safeOccasion||"Treat")+" ✨");
 const heading=audience==="everyone"?(match?(publicHeading[match.key]||match.heading("")):"A Little Something Special! ✨"):(match?match.heading(safeName):"A Little Something Special"+(safeName?", "+safeName:"")+"! ✨");
 const intro=audience==="everyone"?"To celebrate <b>"+(safeOccasion||"this special moment")+"</b>, we’re sharing a little something special with our VALE BEAUTY customers.":(match&&["birthday","anniversary","wedding","newbaby","graduation"].includes(match.key))?"As a little gift from <b>"+esc(businessName)+"</b>, we’d love to celebrate this special moment with you.":"As a little gift from <b>"+esc(businessName)+"</b>, we’d love to share a special offer with you.";
 const body=match?.body||"We’re celebrating <b>"+(safeOccasion||"a special occasion")+"</b>, and we thought you deserved a little extra love from us.";
 const names=serviceNames(groups,allServices);
 const offer=groups.length===1?"Enjoy <b>"+formatValue(groups[0])+"</b>"+(names.length?" on "+names.map(esc).join(", "):"")+".":"Enjoy these special offers:<ul>"+groups.map(g=>"<li><b>"+esc(formatValue(g))+"</b>"+(serviceNames([g],allServices).length?" on "+serviceNames([g],allServices).map(esc).join(", "):"")+"</li>").join("")+"</ul>";
 return {subject:title,html:"<h2>"+heading+"</h2><p>"+body+"</p><p>"+intro+"</p><p>"+offer+"</p><p>We’d love to see you at VALE BEAUTY and help you enjoy a little time for yourself. ✨</p>",occasionType:match?.key||"custom",recognized:!!match};
}
