function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function normalize(v=""){return String(v).trim().toLowerCase().normalize("NFKD").replace(/[\u064B-\u065F\u0670]/g,"").replace(/[ًٌٍَُِّْـ]/g,"")}
const patterns=[
 {key:"birthday",terms:["birthday","bday","birth day","عيد ميلاد","ميلاد"],subject:"Happy Birthday from VALE BEAUTY 🎂",heading:n=>"Happy Birthday"+(n?", "+n:"")+"! 🎂",body:"Wishing you a beautiful birthday filled with happiness, love, and beautiful moments."},
 {key:"anniversary",terms:["anniversary","wedding anniversary","عيد زواج","ذكرى زواج","ذكرى الزواج","ذكرى زفاف"],subject:"A Little Anniversary Gift from VALE BEAUTY 💕",heading:n=>"Happy Anniversary"+(n?", "+n:"")+"! 💕",body:"Wishing you both another beautiful year filled with love, happiness, and wonderful memories."},
 {key:"wedding",terms:["wedding","bride","bridal","getting married","getting married soon","wedding soon","upcoming wedding","wedding coming up","going to marry","going to be married","about to get married","soon to be married","soon-to-be married","marrying","marry soon","engagement","engaged","engagement coming up","engagement soon","getting engaged","getting engaged soon","زواج","زفاف","عرس","عروس","خطوبة","مخطوبة","قريب زواج","زواج قريب","قرب الزواج","قرب زفاف"],subject:"A Little Celebration from VALE BEAUTY 💍",heading:n=>"Congratulations"+(n?", "+n:"")+"! 💍",body:"Wishing you a beautiful celebration and all the happiness in this exciting chapter."},
 {key:"ramadan",terms:["ramadan","رمضان"],subject:"Ramadan Mubarak from VALE BEAUTY 🌙",heading:n=>"Ramadan Mubarak"+(n?", "+n:"")+"! 🌙",body:"Wishing you a peaceful, joyful Ramadan filled with beautiful moments and blessings."},
 {key:"labour",terms:["labour day","labor day","عيد العمال"],subject:"A Little Labour Day Treat from VALE BEAUTY ✨",heading:()=>"Happy Labour Day! ✨",body:"We hope you enjoy a relaxing long weekend and a little time for yourself."},
 {key:"holycross",terms:["holy cross day","feast of the exaltation of the holy cross","exaltation of the holy cross","feast of the cross","holy cross","عيد الصليب","عيد ارتفاع الصليب","رفع الصليب","عيد الصليب المقدس"],subject:"A Little Holy Cross Day Gift from VALE BEAUTY ✝️",heading:n=>"Happy Holy Cross Day"+(n?", "+n:"")+"! ✝️",body:"Wishing you a peaceful and beautiful Holy Cross Day filled with faith, love, and meaningful moments."},
 {key:"ashwednesday",terms:["ash wednesday","ash wednesday coming","أربعاء الرماد","الأربعاء الرمادي"],subject:"Ash Wednesday from VALE BEAUTY 🕊️",heading:n=>"Blessings for Ash Wednesday"+(n?", "+n:"")+" 🕊️",body:"Wishing you a peaceful and meaningful Ash Wednesday as the Lenten season begins."},
 {key:"palm sunday",terms:["palm sunday","passion sunday","أحد الشعانين","أحد السعانين","أحد الشعانين المقدس"],subject:"Blessings for Palm Sunday from VALE BEAUTY 🌿",heading:n=>"Blessings for Palm Sunday"+(n?", "+n:"")+"! 🌿",body:"Wishing you a peaceful and blessed Palm Sunday."},
 {key:"holyweek",terms:["holy week","passion week","الأسبوع المقدس","اسبوع الآلام","أسبوع الآلام"],subject:"Blessings for Holy Week from VALE BEAUTY 🕊️",heading:n=>"Blessings for Holy Week"+(n?", "+n:"")+" 🕊️",body:"Wishing you a peaceful and reflective Holy Week."},
 {key:"maundythursday",terms:["maundy thursday","holy thursday","great thursday","الخميس المقدس","خميس العهد"],subject:"Blessings for Holy Thursday from VALE BEAUTY 🕊️",heading:n=>"Blessings for Holy Thursday"+(n?", "+n:"")+" 🕊️",body:"Wishing you a peaceful and meaningful Holy Thursday."},
 {key:"goodfriday",terms:["good friday","holy friday","great friday","الجمعة العظيمة","الجمعة الحزينة"],subject:"Blessings for Good Friday from VALE BEAUTY 🕊️",heading:n=>"Blessings for Good Friday"+(n?", "+n:"")+" 🕊️",body:"Wishing you a peaceful and reflective Good Friday."},
 {key:"easter",terms:["easter","easter sunday","pascha","resurrection sunday","عيد الفصح","عيد القيامة","الفصح","القيامة"],subject:"Happy Easter from VALE BEAUTY 🌷",heading:n=>"Happy Easter"+(n?", "+n:"")+"! 🌷",body:"Wishing you a beautiful Easter filled with peace, hope, joy, and new beginnings."},
 {key:"eastermonday",terms:["easter monday","اثنين الفصح","اثنين القيامة"],subject:"A Little Easter Monday Treat from VALE BEAUTY 🌷",heading:n=>"Happy Easter Monday"+(n?", "+n:"")+"! 🌷",body:"Wishing you a peaceful Easter Monday and a little time for yourself."},
 {key:"ascension",terms:["ascension day","ascension of the lord","the ascension","عيد الصعود","صعود الرب"],subject:"Blessings for the Ascension from VALE BEAUTY ✨",heading:n=>"Blessings for the Ascension"+(n?", "+n:"")+"! ✨",body:"Wishing you a peaceful and blessed celebration of the Ascension of the Lord."},
 {key:"pentecost",terms:["pentecost","whitsunday","whit sunday","عيد العنصرة","العنصرة","عيد حلول الروح القدس"],subject:"Blessings for Pentecost from VALE BEAUTY 🔥",heading:n=>"Blessings for Pentecost"+(n?", "+n:"")+"! 🔥",body:"Wishing you a joyful and blessed Pentecost filled with peace and hope."},
 {key:"trinity",terms:["trinity sunday","most holy trinity","holy trinity","أحد الثالوث","الثالوث الأقدس"],subject:"Blessings for Trinity Sunday from VALE BEAUTY ✨",heading:n=>"Blessings for Trinity Sunday"+(n?", "+n:"")+"! ✨",body:"Wishing you a peaceful and blessed Trinity Sunday."},
 {key:"corpuschristi",terms:["corpus christi","body and blood of christ","most holy body and blood","feast of corpus christi","عيد القربان","جسد الرب ودمه","جسد المسيح ودمه"],subject:"Blessings for Corpus Christi from VALE BEAUTY ✨",heading:n=>"Blessings for Corpus Christi"+(n?", "+n:"")+"! ✨",body:"Wishing you a beautiful and blessed celebration of the Body and Blood of Christ."},
 {key:"sacredheart",terms:["sacred heart","most sacred heart of jesus","heart of jesus","قلب يسوع","القلب الأقدس","قلب المسيح"],subject:"Blessings for the Sacred Heart from VALE BEAUTY ❤️",heading:n=>"Blessings for the Sacred Heart"+(n?", "+n:"")+"! ❤️",body:"Wishing you a peaceful and blessed celebration of the Sacred Heart of Jesus."},
 {key:"immaculateheart",terms:["immaculate heart","immaculate heart of mary","قلب مريم الطاهر","قلب مريم البريء"],subject:"Blessings from VALE BEAUTY 💙",heading:n=>"Blessings for the Immaculate Heart"+(n?", "+n:"")+"! 💙",body:"Wishing you a peaceful and beautiful celebration of the Immaculate Heart of Mary."},
 {key:"holytrinity",terms:["holy trinity","الثالوث المقدس","الثالوث الأقدس"],subject:"Blessings for the Holy Trinity from VALE BEAUTY ✨",heading:n=>"Blessings for the Holy Trinity"+(n?", "+n:"")+"! ✨",body:"Wishing you a peaceful and blessed celebration."},
 {key:"transfiguration",terms:["transfiguration","transfiguration of the lord","تجلي الرب","التجلي"],subject:"Blessings for the Transfiguration from VALE BEAUTY ✨",heading:n=>"Blessings for the Transfiguration"+(n?", "+n:"")+"! ✨",body:"Wishing you a beautiful and blessed celebration of the Transfiguration of the Lord."},
 {key:"exaltation",terms:["holy cross day","feast of the exaltation of the holy cross","exaltation of the holy cross","feast of the cross","holy cross","exaltation of the cross","عيد الصليب","عيد ارتفاع الصليب","رفع الصليب","عيد الصليب المقدس"],subject:"A Little Holy Cross Day Gift from VALE BEAUTY ✝️",heading:n=>"Happy Holy Cross Day"+(n?", "+n:"")+"! ✝️",body:"Wishing you a peaceful and beautiful Holy Cross Day filled with faith, love, and meaningful moments."},
 {key:"nativitymary",terms:["nativity of mary","nativity of the blessed virgin mary","birth of mary","ميلاد العذراء","مولد العذراء","ميلاد مريم العذراء"],subject:"Blessings from VALE BEAUTY 💙",heading:n=>"Blessings for the Nativity of Mary"+(n?", "+n:"")+"! 💙",body:"Wishing you a peaceful and blessed celebration of the Nativity of the Blessed Virgin Mary."},
 {key:"annunciation",terms:["annunciation","annunciation of the lord","البشارة","بشارة العذراء","بشارة الرب","عيد البشارة"],subject:"Blessings for the Annunciation from VALE BEAUTY 💙",heading:n=>"Blessings for the Annunciation"+(n?", "+n:"")+"! 💙",body:"Wishing you a peaceful and blessed celebration of the Annunciation."},
 {key:"assumption",terms:["assumption","assumption of mary","assumption of the blessed virgin mary","انتقال العذراء","عيد انتقال العذراء","صعود العذراء"],subject:"Blessings for the Assumption from VALE BEAUTY 💙",heading:n=>"Blessings for the Assumption"+(n?", "+n:"")+"! 💙",body:"Wishing you a beautiful and blessed celebration of the Assumption of Mary."},
 {key:"immaculateconception",terms:["immaculate conception","عيد الحبل بلا دنس","الحبل بلا دنس"],subject:"Blessings for the Immaculate Conception from VALE BEAUTY 💙",heading:n=>"Blessings for the Immaculate Conception"+(n?", "+n:"")+"! 💙",body:"Wishing you a peaceful and blessed celebration."},
 {key:"allsaints",terms:["all saints day","all saints' day","all saints","عيد جميع القديسين","عيد القديسين"],subject:"Blessings for All Saints' Day from VALE BEAUTY ✨",heading:n=>"Blessings for All Saints' Day"+(n?", "+n:"")+"! ✨",body:"Wishing you a beautiful and blessed All Saints' Day."},
 {key:"allsouls",terms:["all souls day","all souls' day","day of the dead","commemoration of all the faithful departed","عيد جميع الأرواح","يوم الموتى","ذكرى الموتى"],subject:"A Day of Remembrance from VALE BEAUTY 🕊️",heading:n=>"Remembering Our Loved Ones"+(n?", "+n:"")+" 🕊️",body:"Wishing you a peaceful day of remembrance and prayer for those we love."},
 {key:"christking",terms:["christ the king","feast of christ the king","christ the king sunday","المسيح الملك","عيد المسيح الملك"],subject:"Blessings for Christ the King from VALE BEAUTY 👑",heading:n=>"Blessings for Christ the King"+(n?", "+n:"")+"! 👑",body:"Wishing you a peaceful and blessed celebration of Christ the King."},
 {key:"epiphany",terms:["epiphany","feast of the epiphany","three kings","three kings day","theophany","عيد الغطاس","الغطاس","الظهور الإلهي","عيد الظهور الإلهي"],subject:"Blessings for Epiphany from VALE BEAUTY ✨",heading:n=>"Blessings for Epiphany"+(n?", "+n:"")+"! ✨",body:"Wishing you a joyful and blessed Epiphany."},
 {key:"baptismlord",terms:["baptism of the lord","baptism of jesus","معمودية الرب","عيد معمودية الرب"],subject:"Blessings for the Baptism of the Lord from VALE BEAUTY ✨",heading:n=>"Blessings for the Baptism of the Lord"+(n?", "+n:"")+"! ✨",body:"Wishing you a peaceful and blessed celebration."},
 {key:"presentation",terms:["presentation of the lord","presentation in the temple","candlemas","meeting of the lord","تقدمة الرب","تقديم الرب في الهيكل","عيد الشموع"],subject:"Blessings from VALE BEAUTY ✨",heading:n=>"Blessings for the Presentation of the Lord"+(n?", "+n:"")+"! ✨",body:"Wishing you a peaceful and blessed celebration."},
 {key:"stjoseph",terms:["saint joseph","st joseph","st. joseph","sleeps of st joseph","يوسف النجار","القديس يوسف","عيد مار يوسف"],subject:"Blessings for Saint Joseph's Day from VALE BEAUTY ✨",heading:n=>"Happy Saint Joseph's Day"+(n?", "+n:"")+"! ✨",body:"Wishing you a peaceful and blessed Saint Joseph's Day."},
 {key:"johnbaptist",terms:["saint john the baptist","st john the baptist","nativity of saint john the baptist","ميلاد يوحنا المعمدان","عيد يوحنا المعمدان","القديس يوحنا المعمدان"],subject:"Blessings for Saint John the Baptist from VALE BEAUTY ✨",heading:n=>"Blessings for Saint John the Baptist"+(n?", "+n:"")+"! ✨",body:"Wishing you a peaceful and blessed celebration."},
 {key:"peterpaul",terms:["saints peter and paul","saint peter and paul","st peter and paul","القديسين بطرس وبولس","عيد بطرس وبولس"],subject:"Blessings for Saints Peter and Paul from VALE BEAUTY ✨",heading:n=>"Blessings for Saints Peter and Paul"+(n?", "+n:"")+"! ✨",body:"Wishing you a peaceful and blessed celebration."},
 {key:"stnicholas",terms:["saint nicholas","st nicholas","st. nicholas","feast of saint nicholas","القديس نيقولاوس","مار نيقولا","عيد مار نيقولا"],subject:"A Little Saint Nicholas Gift from VALE BEAUTY 🎁",heading:n=>"Happy Saint Nicholas Day"+(n?", "+n:"")+"! 🎁",body:"Wishing you a joyful and blessed Saint Nicholas Day."},
 {key:"stpatrick",terms:["saint patrick","st patrick","st. patrick","saint patrick's day","عيد القديس باتريك","عيد مار بطرس"],subject:"Happy Saint Patrick's Day from VALE BEAUTY 🍀",heading:n=>"Happy Saint Patrick's Day"+(n?", "+n:"")+"! 🍀",body:"Wishing you a joyful Saint Patrick's Day."},
 {key:"christmas",terms:["christmas","xmas","nativity of the lord","nativity of christ","عيد الميلاد المجيد","عيد الميلاد المسيحي","كريسماس","ميلاد المسيح"],subject:"Merry Christmas from VALE BEAUTY 🎄",heading:n=>"Merry Christmas"+(n?", "+n:"")+"! 🎄",body:"Wishing you a warm, joyful Christmas filled with peace, love, and beautiful moments."},
 {key:"advent",terms:["advent","first sunday of advent","second sunday of advent","third sunday of advent","fourth sunday of advent","زمن المجيء","المجيء","عيد المجيء"],subject:"Blessings for Advent from VALE BEAUTY 🕯️",heading:n=>"Blessings for Advent"+(n?", "+n:"")+"! 🕯️",body:"Wishing you a peaceful Advent season filled with hope, faith, joy, and love."},
 {key:"lent",terms:["lent","lenten season","great lent","الصوم الكبير","الصوم الأربعيني","زمن الصوم"],subject:"Blessings for Lent from VALE BEAUTY 🕊️",heading:n=>"Blessings for Lent"+(n?", "+n:"")+" 🕊️",body:"Wishing you a peaceful and meaningful Lenten season."},
 {key:"orthodoxchristmas",terms:["orthodox christmas","orthodox nativity","عيد الميلاد الشرقي","ميلاد شرقي","عيد الميلاد الأرثوذكسي"],subject:"Merry Orthodox Christmas from VALE BEAUTY 🎄",heading:n=>"Merry Orthodox Christmas"+(n?", "+n:"")+"! 🎄",body:"Wishing you a joyful and blessed Christmas filled with peace, love, and beautiful moments."},
 {key:"orthodoxeaster",terms:["orthodox easter","orthodox pascha","eastern easter","الفصح الشرقي","عيد القيامة الشرقي","قيامة شرقية"],subject:"Happy Orthodox Easter from VALE BEAUTY 🌷",heading:n=>"Happy Orthodox Easter"+(n?", "+n:"")+"! 🌷",body:"Wishing you a beautiful and blessed Orthodox Easter filled with hope and joy."},
 {key:"christianfeast",terms:["feast day","feast of saint","feast of st ","saint day","saints day","memorial of saint","solemnity of saint","holy day","holy feast","عيد القديس","عيد القديسة","القديس ","القديسة ","مار "],subject:"Blessings from VALE BEAUTY ✨",heading:n=>"Blessings for "+(n||"this special day")+" ✨",body:"Wishing you a peaceful and blessed celebration. May this special day bring you faith, joy, peace, and beautiful moments."},
 {key:"eid",terms:["eid","eid al-fitr","eid al adha","عيد الفطر","عيد الاضحى","عيد الأضحى","عيد"],subject:"Eid Mubarak from VALE BEAUTY ✨",heading:n=>"Eid Mubarak"+(n?", "+n:"")+"! ✨",body:"Wishing you and your loved ones a beautiful Eid filled with happiness and joy."},
 {key:"canadaday",terms:["canada day","july 1","عيد كندا","يوم كندا"],subject:"A Little Canada Day Treat from VALE BEAUTY 🍁",heading:()=>"Happy Canada Day! 🍁",body:"Wishing you a beautiful Canada Day filled with sunshine, happiness, and a little time for yourself."},
 {key:"familyday",terms:["family day","ontario family day","يوم العائلة"],subject:"Happy Family Day from VALE BEAUTY 💕",heading:n=>"Happy Family Day"+(n?", "+n:"")+"! 💕",body:"Wishing you a beautiful Family Day filled with love and time with the people who matter most."},
 {key:"victoriaday",terms:["victoria day","victoria day weekend","عيد فيكتوريا"],subject:"A Little Victoria Day Treat from VALE BEAUTY 🌸",heading:()=> "Happy Victoria Day! 🌸",body:"Wishing you a beautiful long weekend and a little time for yourself."},
 {key:"civic",terms:["civic holiday","civic holiday weekend","simcoe day","bc day","heritage day","new brunswick day","alberta heritage day","saskatchewan day","british columbia day","يوم العطلة المدنية"],subject:"A Little Civic Holiday Treat from VALE BEAUTY ✨",heading:()=> "Happy Civic Holiday! ✨",body:"Wishing you a relaxing long weekend and a little time for yourself."},
 {key:"truthreconciliation",terms:["national day for truth and reconciliation","truth and reconciliation day","orange shirt day","day for truth and reconciliation","يوم الحقيقة والمصالحة","يوم القميص البرتقالي"],subject:"National Day for Truth and Reconciliation",heading:()=> "National Day for Truth and Reconciliation 🧡",body:"A day to remember, learn, listen, and reflect on the history and legacy of residential schools and Indigenous communities."},
 {key:"remembrance",terms:["remembrance day","remembrance day canada","armistice day","يوم الذكرى","يوم إحياء الذكرى"],subject:"Remembrance Day",heading:()=> "Lest We Remember ❤️",body:"Taking a moment to remember and honour those who served and sacrificed."},
 {key:"canada",terms:["canada day","canada day weekend","july 1","dominion day","عيد كندا","يوم كندا"],subject:"A Little Canada Day Treat from VALE BEAUTY 🍁",heading:()=> "Happy Canada Day! 🍁",body:"Wishing you a beautiful Canada Day filled with sunshine, happiness, and a little time for yourself."},
 {key:"boxing",terms:["boxing day","boxing day weekend","يوم الصناديق"],subject:"A Little Boxing Day Treat from VALE BEAUTY 🎁",heading:()=> "Happy Boxing Day! 🎁",body:"We hope you enjoy a relaxing Boxing Day and a little time for yourself."},
 {key:"newyearseve",terms:["new year's eve","new years eve","new year's eve party","رأس السنة الميلادية","ليلة رأس السنة","ليلة السنة الجديدة"],subject:"Happy New Year's Eve from VALE BEAUTY ✨",heading:()=> "Happy New Year's Eve! ✨",body:"Wishing you a beautiful night and a wonderful start to the year ahead."},
 {key:"canadianremembrance",terms:["canadian veterans week","veterans week canada","veterans week","أسبوع المحاربين القدامى"],subject:"Veterans' Week in Canada",heading:()=> "Honouring Canada's Veterans ❤️",body:"Taking time to remember and honour the people who served Canada."},
 {key:"indigenous",terms:["national indigenous peoples day","indigenous peoples day","عيد الشعوب الأصلية","يوم الشعوب الأصلية"],subject:"National Indigenous Peoples Day",heading:()=> "National Indigenous Peoples Day 🌿",body:"A day to recognize and celebrate the cultures, traditions, languages, contributions, and heritage of First Nations, Inuit, and Métis peoples."},
 {key:"multicultural",terms:["canadian multiculturalism day","multiculturalism day","اليوم الكندي للتعددية الثقافية"],subject:"Canadian Multiculturalism Day",heading:()=> "Happy Canadian Multiculturalism Day! 🌎",body:"Celebrating the many cultures and communities that help make Canada what it is."},
 {key:"acadian",terms:["national acadian day","acadian day","يوم الأكاديين","اليوم الأكادي"],subject:"Happy National Acadian Day from VALE BEAUTY 💙",heading:()=> "Happy National Acadian Day! 💙",body:"Wishing you a beautiful celebration of Acadian culture, heritage, and community."},
 {key:"saintjean",terms:["saint-jean-baptiste day","saint jean baptiste day","fete nationale du quebec","fête nationale du québec","fete nationale","عيد القديس يوحنا المعمدان في كندا"],subject:"Happy Saint-Jean-Baptiste Day from VALE BEAUTY 💙",heading:()=> "Happy Saint-Jean-Baptiste Day! 💙",body:"Wishing you a joyful celebration of Francophone culture and community."},
 {key:"emancipation",terms:["emancipation day","emancipation day canada","يوم التحرر"],subject:"Emancipation Day in Canada",heading:()=> "Emancipation Day 🖤",body:"A day to reflect on the history, resilience, and contributions of Black communities in Canada."},
 {key:"armedforces",terms:["canadian armed forces day","armed forces day canada","يوم القوات المسلحة الكندية"],subject:"Canadian Armed Forces Day",heading:()=> "Honouring Canada's Armed Forces 🇨🇦",body:"Taking a moment to recognize the service and contributions of Canada's Armed Forces."},
 {key:"veterans",terms:["veterans week","veterans week canada","canadian veterans week","أسبوع المحاربين القدامى"],subject:"Veterans' Week in Canada",heading:()=> "Honouring Canada's Veterans ❤️",body:"Taking time to remember and honour the people who served Canada."},
 {key:"terrorismvictims",terms:["national day of remembrance for victims of terrorism","victims of terrorism day","يوم ذكرى ضحايا الإرهاب"],subject:"National Day of Remembrance",heading:()=> "Remembering Those Affected 🕊️",body:"A day to remember the victims of terrorism and reflect on the lives and communities affected."},
 {key:"vimy",terms:["vimy day","vimy ridge day","يوم فيمي"],subject:"Vimy Day",heading:()=> "Remembering Vimy Ridge ❤️",body:"A day to remember the Canadians who served and sacrificed at Vimy Ridge."},
 {key:"halloween",terms:["halloween","hallowe'en","all hallows eve","عيد الهالوين","ليلة جميع القديسين"],subject:"A Little Halloween Treat from VALE BEAUTY 🎃",heading:()=> "Happy Halloween! 🎃",body:"Wishing you a fun and spooky Halloween filled with sweet moments."},
 {key:"earthday",terms:["earth day","يوم الأرض"],subject:"Happy Earth Day from VALE BEAUTY 🌎",heading:()=> "Happy Earth Day! 🌎",body:"A little reminder to celebrate and care for the beautiful world around us."},
 {key:"womensday",terms:["international women's day","international womens day","women's day","womens day","يوم المرأة","عيد المرأة"],subject:"A Little Celebration of You from VALE BEAUTY 💐",heading:n=>"Happy Women's Day"+(n?", "+n:"")+"! 💐",body:"Today is a beautiful reminder to celebrate yourself, your strength, and everything that makes you you."},
 {key:"pride",terms:["pride month","pride day","pride weekend","pride season","شهر الفخر","يوم الفخر"],subject:"Celebrating Pride 🌈",heading:()=> "Happy Pride! 🌈",body:"Wishing you a beautiful celebration of love, inclusion, dignity, and being yourself."},
 {key:"thanksgiving",terms:["thanksgiving","عيد الشكر"],subject:"A Little Thanksgiving Treat from VALE BEAUTY 🧡",heading:n=>"Happy Thanksgiving"+(n?", "+n:"")+"! 🧡",body:"Wishing you a warm and beautiful Thanksgiving filled with gratitude and good moments."},
 {key:"easter",terms:["easter","عيد الفصح"],subject:"A Little Easter Treat from VALE BEAUTY 🌷",heading:n=>"Happy Easter"+(n?", "+n:"")+"! 🌷",body:"Wishing you a beautiful Easter filled with peace, happiness, and fresh beginnings."},
 {key:"blackfriday",terms:["black friday","black-friday"],subject:"Black Friday Beauty Treat from VALE BEAUTY 🖤",heading:()=>"A Little Black Friday Treat! 🖤",body:"We’re celebrating with a special beauty offer made just for you."},
 {key:"womensday",terms:["international women's day","international womens day","women's day","womens day","يوم المرأة","عيد المرأة"],subject:"A Little Celebration of You from VALE BEAUTY 💐",heading:n=>"Happy Women's Day"+(n?", "+n:"")+"! 💐",body:"Today is a beautiful reminder to celebrate yourself, your strength, and everything that makes you you."},
 {key:"valentines",terms:["valentine","valentine's day","valentines day","عيد الحب"],subject:"A Little Love from VALE BEAUTY 💕",heading:n=>"Happy Valentine's Day"+(n?", "+n:"")+"! 💕",body:"Sending a little extra love your way and wishing you a beautiful day."},
 {key:"mothers",terms:["mother's day","mothers day","عيد الام","عيد الأم"],subject:"A Little Mother's Day Gift from VALE BEAUTY 💐",heading:n=>"Happy Mother's Day"+(n?", "+n:"")+"! 💐",body:"Wishing you a beautiful day filled with love, appreciation, and a little time for yourself."},
 {key:"fathers",terms:["father's day","fathers day","عيد الاب","عيد الأب"],subject:"A Little Father's Day Gift from VALE BEAUTY ✨",heading:n=>"Happy Father's Day"+(n?", "+n:"")+"! ✨",body:"Wishing you a wonderful Father's Day and a beautiful day with the people you love."},
 {key:"christmas",terms:["christmas","xmas","عيد الميلاد المجيد","كريسماس"],subject:"Merry Christmas from VALE BEAUTY 🎄",heading:n=>"Merry Christmas"+(n?", "+n:"")+"! 🎄",body:"Wishing you a warm, joyful holiday season filled with beautiful moments."},
 {key:"newyear",terms:["new year","new year's","رأس السنة","راس السنة","السنة الجديدة"],subject:"Happy New Year from VALE BEAUTY ✨",heading:n=>"Happy New Year"+(n?", "+n:"")+"! ✨",body:"Wishing you a beautiful year ahead filled with happiness, health, and wonderful new memories."},
 {key:"backtoschool",terms:["back to school","back-to-school","العودة للمدارس","العودة للمدرسة"],subject:"Back-to-School Treat from VALE BEAUTY ✨",heading:n=>"A Little Back-to-School Treat"+(n?", "+n:"")+"! ✨",body:"A new season is here, so we thought you deserved a little self-care before the busy days begin."},
 {key:"newbaby",terms:["new baby","baby shower","newborn","مولود","بيبي","ولادة"],subject:"A Little Gift for Your Special Moment from VALE BEAUTY 💕",heading:n=>"Congratulations"+(n?", "+n:"")+"! 💕",body:"Wishing you and your family so much happiness during this beautiful new chapter."},
 {key:"graduation",terms:["graduation","graduate","تخرج","تخرجك"],subject:"Congratulations from VALE BEAUTY 🎓",heading:n=>"Congratulations"+(n?", "+n:"")+"! 🎓",body:"You worked for this moment, and you deserve to celebrate it. Wishing you every success in what comes next."}
];
const temporalTerms=["going to","gonna","will","will be","going","soon","coming up","coming soon","next week","next month","next weekend","this week","this weekend","tomorrow","upcoming","in a few days","in a week","in two weeks","later this week","later this month","قريبا","قريب","الأسبوع القادم","الأسبوع الجاي","الشهر القادم","الشهر الجاي","الأيام القادمة","الاسبوع القادم","الاسبوع الجاي","غدا","بكرة","بكرا"];
function hasUpcomingContext(occasion=""){const n=normalize(occasion);return temporalTerms.some(t=>n.includes(normalize(t)))}
function classify(occasion=""){const n=normalize(occasion);return patterns.find(p=>p.terms.some(t=>n.includes(normalize(t))))||null}
function formatValue(g){return g.kind==="percent"?Number(g.value)+"% off":"$"+Number(g.value).toFixed(2)+" off"}
function serviceNames(groups,allServices=[]){return groups.flatMap(g=>(g.serviceIds||[]).map(id=>allServices.find(s=>s.id===id)?.name||id)).filter(Boolean)}
export function buildDiscountMessage({name="",occasion="",groups=[],allServices=[],businessName="VALE BEAUTY VK",audience="personal"}={}){
 const raw=String(occasion||"").trim(),match=classify(raw),upcoming=hasUpcomingContext(raw),person=String(name||"").trim(),safeName=esc(person),safeOccasion=esc(raw);
 const publicSubject={birthday:"A Birthday Treat from VALE BEAUTY 🎂",anniversary:"A Little Anniversary Celebration from VALE BEAUTY 💕",wedding:"A Little Celebration from VALE BEAUTY 💍",newbaby:"A Little Celebration from VALE BEAUTY 💕",graduation:"A Little Celebration from VALE BEAUTY 🎓"};
 const publicHeading={birthday:"A Little Birthday Treat for You! 🎂",anniversary:"A Little Anniversary Treat for You! 💕",wedding:"A Little Celebration for You! 💍",newbaby:"A Little Celebration for You! 💕",graduation:"A Little Celebration for You! 🎓"};
 const upcomingSubjects={birthday:"Your Birthday Is Coming Up 🎂",anniversary:"Your Anniversary Is Coming Up 💕",wedding:"Your Special Day Is Coming Up 💍",newbaby:"A Special New Chapter Is Coming Up 💕",graduation:"Your Graduation Is Coming Up 🎓",christmas:"Christmas Is Coming Up 🎄",easter:"Easter Is Coming Up 🌷",holycross:"Holy Cross Day Is Coming Up ✝️",exaltation:"Holy Cross Day Is Coming Up ✝️",canada:"Canada Day Is Coming Up 🍁",thanksgiving:"Thanksgiving Is Coming Up 🧡",valentines:"Valentine’s Day Is Coming Up 💕",mothers:"Mother’s Day Is Coming Up 💐",fathers:"Father’s Day Is Coming Up ✨",newyear:"The New Year Is Coming Up ✨"};
 const title=audience==="everyone"&&upcoming&&match?.key&&upcomingSubjects[match.key]?upcomingSubjects[match.key]:(audience==="everyone"&&match?.key&&publicSubject[match.key]?publicSubject[match.key]:(match?.subject||(raw?businessName+" — A Special "+safeOccasion+" ✨":businessName+" — A Special Offer Just for You ✨")));
 const upcomingHeadings={birthday:"Your Birthday Is Coming Up! 🎂",anniversary:"Your Anniversary Is Coming Up! 💕",wedding:"Your Special Day Is Coming Up! 💍",newbaby:"A Beautiful New Chapter Is Coming Up! 💕",graduation:"Your Graduation Is Coming Up! 🎓",christmas:"Christmas Is Coming Up! 🎄",easter:"Easter Is Coming Up! 🌷",exaltation:"Holy Cross Day Is Coming Up! ✝️",canada:"Canada Day Is Coming Up! 🍁",thanksgiving:"Thanksgiving Is Coming Up! 🧡",valentines:"Valentine’s Day Is Coming Up! 💕",mothers:"Mother’s Day Is Coming Up! 💐",fathers:"Father’s Day Is Coming Up! ✨",newyear:"The New Year Is Coming Up! ✨"};
 const heading=audience==="everyone"?(upcoming&&match?.key&&upcomingHeadings[match.key]?upcomingHeadings[match.key]:(match?(publicHeading[match.key]||match.heading("")):"A Special Offer Just for You! ✨")):(upcoming&&match?.key&&upcomingHeadings[match.key]?upcomingHeadings[match.key]:(match?match.heading(safeName):"A Special Offer Just for You"+(safeName?", "+safeName:"")+"! ✨"));
 const intro=audience==="everyone"?(safeOccasion?"To celebrate <b>"+safeOccasion+"</b>, we’re sharing a little something special with our VALE BEAUTY customers.":"We have a special offer available for our VALE BEAUTY customers, and we wanted to make sure you didn’t miss it."):((match&&["birthday","anniversary","wedding","newbaby","graduation"].includes(match.key))?"As a little gift from <b>"+esc(businessName)+"</b>, we’d love to celebrate this special moment with you.":"As a little gift from <b>"+esc(businessName)+"</b>, we’d love to share a special offer with you.");
 const body=upcoming&&match?("Your <b>"+esc(match.key==="wedding"?"special day":match.key.replace(/([A-Z])/g," $1"))+"</b> is coming up, and we thought this would be the perfect time to celebrate with you."):match?.body||(raw?"We’re celebrating <b>"+safeOccasion+"</b>, and we thought you deserved a little extra love from us.":"We wanted to share a special offer with you as a little thank-you from VALE BEAUTY.");
 const names=serviceNames(groups,allServices);
 const maxGroup=groups.reduce((best,g)=>!best||Number(g.value)>Number(best.value)?g:best,null);
 const maxOffer=maxGroup?(maxGroup.kind==="percent"?"up to <b>"+Number(maxGroup.value)+"% off</b>":"savings of up to <b>$"+Number(maxGroup.value).toFixed(2)+"</b>"):"";
 const offer=audience==="everyone"&&!match&&!raw?(maxOffer?"We currently have special offers with "+maxOffer+".":"We currently have special offers available for you."):(groups.length===1?"Enjoy <b>"+formatValue(groups[0])+"</b>"+(names.length?" on "+names.map(esc).join(", "):"")+".":"Enjoy these special offers:<ul>"+groups.map(g=>"<li><b>"+esc(formatValue(g))+"</b>"+(serviceNames([g],allServices).length?" on "+serviceNames([g],allServices).map(esc).join(", "):"")+"</li>").join("")+"</ul>");
 return {subject:title,html:"<h2>"+heading+"</h2><p>"+body+"</p><p>"+intro+"</p><p>"+offer+"</p><p>We’d love to see you at VALE BEAUTY and help you enjoy a little time for yourself. ✨</p>",occasionType:match?.key||"custom",recognized:!!match};
}
