"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
const KEY="vale-customer-session";
export default function RegisterClient(){const[email,setEmail]=useState(""),[name,setName]=useState(""),[profiles,setProfiles]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),router=useRouter();
 useEffect(()=>{const e=email.trim().toLowerCase();setSelected(null);if(!e||!e.includes("@")){setProfiles([]);setName("");return}let dead=false;setLoading(true);fetch(`/api/customers?email=${encodeURIComponent(e)}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(dead)return;const list=j.customers||[];setProfiles(list);if(list.length===1){setSelected(list[0]);setName(list[0].name)}}).catch(()=>{if(!dead)setProfiles([])}).finally(()=>{if(!dead)setLoading(false)});return()=>{dead=true}},[email]);
 function choose(p){setSelected(p);setName(p.name);setProfiles([]);setMsg("");}
 async function submit(e){e.preventDefault();if(!name.trim())return setMsg("Please choose your profile or enter your full name.");setBusy(true);setMsg("");try{const r=await fetch("/api/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email})}),j=await r.json();if(!r.ok)throw Error(j.error||"Registration failed.");localStorage.setItem(KEY,JSON.stringify({id:j.customer.id,name:j.customer.name,email:j.customer.email}));window.dispatchEvent(new Event("vale-customer-session-changed"));setMsg("Welcome to VALE BEAUTY ✨");setTimeout(()=>router.push("/services"),450)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="bookingbox" style={{maxWidth:620,marginTop:28}}><form className="form" onSubmit={submit}><label>Email<input required type="email" value={email} onChange={e=>{const next=e.target.value;setEmail(next);setName("");setSelected(null);setMsg("");try{const raw=localStorage.getItem(KEY);if(raw){const old=JSON.parse(raw);if(String(old?.email||"").trim().toLowerCase()!==next.trim().toLowerCase())localStorage.removeItem(KEY)}}catch{}}} autoComplete="email" placeholder="you@example.com"/></label>{loading&&<p className="muted small">Checking customer profiles…</p>}{profiles.length>0&&<div className="profilePicker"><div className="fieldLabel">Choose your customer profile</div><p className="muted small">Select the name already registered with this email.</p>{profiles.map(p=><button type="button" className="profileChoice" key={p.id} onClick={()=>choose(p)}><strong>{p.name}</strong><span>{p.email}</span></button>)}</div>}{!loading&&!selected&&profiles.length===0&&email.includes("@")&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name" placeholder="Your full name"/></label>}{selected&&<label>Full name<input required value={name} readOnly autoComplete="name"/></label>}<button className="btn" disabled={busy||loading}>{busy?"Creating profile…":"Continue"}</button>{msg&&<div className={msg.toLowerCase().includes("welcome")?"success":"error"}>{msg}</div>}</form></div>}
