"use client";
import {useEffect,useMemo,useState} from "react";
import {Calendar,TimeSlots,localIsoDate} from "../../components/AppointmentPicker";
export default function ManageClient({token}){
 const [email,setEmail]=useState(""),[booking,setBooking]=useState(null),[msg,setMsg]=useState(""),[date,setDate]=useState(""),[start,setStart]=useState(""),[blocked,setBlocked]=useState([]),[available,setAvailable]=useState(null),[loading,setLoading]=useState(false),[loadingSlots,setLoadingSlots]=useState(false);
 async function request(action,extra={}){setLoading(true);setMsg("");try{const r=await fetch(`/api/manage/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,action,...extra})});const j=await r.json();if(!r.ok)throw new Error(j.error||"We could not complete that request.");return j}catch(e){setMsg(e.message);return null}finally{setLoading(false)}}
 async function verify(){const j=await request("verify");if(j){setBooking(j.booking);setDate(j.booking.date);setStart(`${String(Math.floor(Number(j.booking.start)/60)).padStart(2,"0")}:${String(Number(j.booking.start)%60).padStart(2,"0")}`);setMsg("")}}
 useEffect(()=>{if(!booking||!date||!booking.canChange)return;let cancelled=false;setLoadingSlots(true);fetch(`/api/bookings?date=${date}&duration=${booking.duration}&excludeBookingId=${encodeURIComponent(booking.id)}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"availability");return j}).then(j=>{if(cancelled)return;const selfStart=Number(booking.start),selfEndWithBuffer=selfStart+Number(booking.duration)+30;const cleanBlocked=(j.blocked||[]).filter(b=>!(date===booking.date&&Number(b.start_minutes)===selfStart&&Number(b.end_minutes)===selfEndWithBuffer));setBlocked(cleanBlocked);setAvailable(null)}).catch(()=>{if(!cancelled){setBlocked([]);setAvailable(null)}}).finally(()=>{if(!cancelled)setLoadingSlots(false)});return()=>{cancelled=true}},[booking,date]);
 async function cancel(){if(!confirm("Cancel this appointment?"))return;const j=await request("cancel");if(j){setMsg(j.message);setBooking(null)}}
 async function reschedule(){const j=await request("reschedule",{date,start});if(j){setMsg(j.message);setBooking(null)}}
 const minDate=useMemo(()=>localIsoDate(new Date()),[]);
 const cancelledByClient=booking?.status==="cancelled"&&booking?.cancelledBy==="client";
 const cancelledByStudio=booking?.status==="cancelled"&&booking?.cancelledBy!=="client";
 return <div className="bookingbox"><form className="form" onSubmit={e=>{e.preventDefault();verify()}}><label>Email used for the booking<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="btn" disabled={loading}>{loading?"Checking…":"Verify"}</button></form>{msg&&<div className="success" style={{marginTop:15}}>{msg}</div>}{booking&&<div className="manageDetails" style={{marginTop:20}}><div className="summary"><strong>{booking.date} · {booking.startLabel}</strong><br/>{booking.items.map((x,i)=><span key={i}>{x.name}{i<booking.items.length-1?" · ":""}</span>)}<br/>Duration: {booking.duration} min · Total: ${Number(booking.total).toFixed(2)}</div>{cancelledByClient?<div className="success" style={{marginTop:12}}><strong>This appointment was cancelled by you.</strong><br/><span>You cannot use this appointment link to make another appointment.</span><div style={{marginTop:12}}><a className="btn" href="/" style={{display:"inline-block",textDecoration:"none"}}>Book a New Appointment</a></div></div>:cancelledByStudio?<div className="error" style={{marginTop:12}}><strong>This appointment was cancelled by the studio.</strong><br/><span>This appointment link is no longer available for changes. To make a new appointment, please book through our website.</span><div style={{marginTop:12}}><a className="btn" href="/" style={{display:"inline-block",textDecoration:"none"}}>Book a New Appointment</a></div></div>:booking.lateNotice?<div className="error" style={{marginTop:12}}><strong>24-hour notice:</strong> Online cancellation and appointment changes are only available until 24 hours before the appointment.</div>:null}{booking.canChange?<><div className="manageActions"><button type="button" className="btn dangerBtn" onClick={cancel} disabled={loading}>Cancel Appointment</button></div><fieldset><legend>Change appointment</legend><label>New date<Calendar value={date} minDate={minDate} duration={booking.duration} ignoreBookingId={booking.id} onChange={v=>{setDate(v);setStart("")}}/></label><div className="timePickerField"><div className="fieldLabel">New start time</div>{date?<TimeSlots date={date} duration={booking.duration} selected={start} onChange={setStart} blocked={blocked} available={available} loading={loadingSlots} ignoreId={booking.id} ignoreStart={booking.start} ignoreDuration={booking.duration} currentStart={date===booking.date?booking.start:null}/>:<p className="muted small">Choose a date first.</p>}</div><button type="button" className="btn" onClick={reschedule} disabled={!date||!start||loading||loadingSlots}>Confirm Change</button></fieldset></>:!cancelledByClient&&!cancelledByStudio?<p className="muted" style={{marginTop:16}}>You can cancel or change your appointment through this private link up to 24 hours before the appointment.</p>:null}</div>}</div>
}