import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {DateTime} from "luxon";
import {allServices,business} from "../../../../lib/services";
const db=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const ok=req=>req.headers.get("x-admin-pin")===process.env.ADMIN_PIN;
export async function GET(req){if(!ok(req))return NextResponse.json({error:"Access denied"},{status:403});try{const c=db();const {data,error}=await c.from("winners").select("id,customer_id,prize_name,service_id,discount_id,starts_at,expires_at,max_uses,uses,active,created_at,updated_at,customer_profiles(name,email),customer_discounts(kind,value,service_ids)").order("created_at",{ascending:false});if(error)throw error;return NextResponse.json({winners:data||[]})}catch(e){console.error(e);return NextResponse.json({error:"Could not load winners."},{status:500})}}
export async function POST(req){if(!ok(req))return NextResponse.json({error:"Access denied"},{status:403});try{const b=await req.json(),action=String(b.action||""),c=db();
 if(action==="deactivate"){const id=String(b.id||"");if(!id)return NextResponse.json({error:"Winner not found."},{status:400});const {data:w,error:we}=await c.from("winners").select("id,customer_id,discount_id").eq("id",id).maybeSingle();if(we)throw we;if(!w)return NextResponse.json({error:"Winner not found."},{status:404});await c.from("winners").update({active:false,updated_at:new Date().toISOString()}).eq("id",id);if(w.discount_id)await c.from("customer_discounts").update({active:false,updated_at:new Date().toISOString()}).eq("id",w.discount_id);await c.from("admin_audit_log").insert({action:"winner_deactivated",entity_type:"winner",entity_id:id,details:{customerId:w.customer_id,discountId:w.discount_id}});return NextResponse.json({message:"Winner gift deactivated."})}
 if(action!=="create")return NextResponse.json({error:"Unsupported winner action."},{status:400});
 const customerId=String(b.customerId||"").trim(),serviceId=String(b.serviceId||"").trim(),prizeName=String(b.prizeName||"").trim();if(!customerId||!serviceId||!prizeName)return NextResponse.json({error:"Choose a customer, prize and service."},{status:400});const service=allServices.find(s=>s.id===serviceId);if(!service)return NextResponse.json({error:"Selected service was not found."},{status:400});const {data:person,error:pe}=await c.from("customer_profiles").select("id,name,email").eq("id",customerId).maybeSingle();if(pe)throw pe;if(!person)return NextResponse.json({error:"Customer profile not found."},{status:404});const starts=DateTime.now().setZone(business.timezone),expires=b.expiresAt?DateTime.fromISO(String(b.expiresAt),{zone:business.timezone}):null;if(expires&&!expires.isValid)return NextResponse.json({error:"Choose a valid expiration date and time."},{status:400});if(expires&&expires<=starts)return NextResponse.json({error:"Expiration must be in the future."},{status:400});const maxUses=b.maxUses===""||b.maxUses==null?null:Number(b.maxUses);if(maxUses!==null&&(!Number.isInteger(maxUses)||maxUses<1))return NextResponse.json({error:"Usage limit must be a positive whole number."},{status:400});const note=`WINNER|${prizeName}`;const {data:discount,error:de}=await c.from("customer_discounts").insert({customer_id:person.id,email:person.email.toLowerCase(),kind:"percent",value:100,starts_at:starts.toUTC().toISO(),expires_at:expires?expires.toUTC().toISO():null,max_uses:maxUses,uses:0,active:true,note,scope:"customer",service_ids:[service.id]}).select("id").single();if(de)throw de;const {data:winner,error:we}=await c.from("winners").insert({customer_id:person.id,prize_name:prizeName,service_id:service.id,discount_id:discount.id,starts_at:starts.toUTC().toISO(),expires_at:expires?expires.toUTC().toISO():null,max_uses:maxUses,uses:0,active:true}).select("id").single();if(we){await c.from("customer_discounts").delete().eq("id",discount.id);throw we}await c.from("admin_audit_log").insert({action:"winner_created",entity_type:"winner",entity_id:winner.id,email:person.email,details:{customerId:person.id,prizeName,serviceId:service.id,serviceName:service.name,maxUses,expiresAt:expires?.toISO()||null}});return NextResponse.json({message:`Winner gift added for ${person.name}.`})
 }catch(e){console.error(e);return NextResponse.json({error:"Could not save winner gift."},{status:500})}}
